### ISSUE TITLE
@pnp/sp-taxonomy@1.3.10 requires a peer of @pnp/logging@1.3.10

### ISSUE THREAD

**Issue by tavikukko** [pnp/pnpjs#1068]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.10      ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

when installing @pnp/sp-taxonomy I get this.
```
npm WARN @pnp/sp-taxonomy@1.3.10 requires a peer of @pnp/logging@1.3.10 but none is installed. You must install peer dependencies yourself.
```
should peer dependecy be @pnp/logging@2.0.3? or is it even compatible?

**Comment by ValerasNarbutas** [comment]
Hi @tavikukko 
not sure about which version should be but automatic peer dependencies install was removed with NPM 3 version. 

try npm install --save-dev @xxxxx/xxxxx@latest
for each one, with the xxxxx referring to the exact text in the peer warning

but this is more for the warning, i am not sure about compatibility

**Comment by patrick-rodgers** [comment]
1.* and 2.* are not compatible. If you need to use the taxonomy stuff you would need to stay in the 1.* set of libraries. The idea being that once the methods are available in Graph we will implement those. The downside is they keep not showing up...

I didn't want to end up having two sets of code that did the same thing in 2.* because they wouldn't do the same stuff or work the same way and that would quickly become confusing for folks.

**Comment by tavikukko** [comment]
Yeah,
now I see. Im using both at the same time, V1 (sp-taxonomy/sp-clientsvc)& V2 (all packages).

Thanks, closing.

**Comment by Ofer-Gal** [comment]
If I have all my PNP on 2.0.4 I will have to go back to 1.3.? just to add taxonomy support?
Is there another way to get a term set terms without changing everything else?
When will taxonomy be part of PNP 2+ ?

**Comment by juliemturner** [comment]
Manually make the calls, just because the PnPJS library is in your project doesn't mean you have to use it, it just simplifies things. 

Also, as a rule we don't monitor closed issues so in the future please start your own new issue, and reference the closed one to add your new question/issue. Thanks!

**Comment by Ofer-Gal** [comment]
Thanks
Do you mean something like this? https://sharepoint.stackexchange.com/questions/116880/how-can-i-get-information-about-a-term-through-javascript
