### ISSUE TITLE
sp.setup works only sometimes? (SitePages problem)

### ISSUE THREAD

**Issue by AdiuTankT72** [pnp/pnpjs#1184]
# Category
- [ ] Enhancement
- [x ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.4 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Following code should setup context properly even on pages inside SitePages
` sp.setup({
      spfxContext: this.context
    });`

### Observed Behavior
The setup sometimes works and sometimes not

### Steps to Reproduce
I recorded a video: https://youtu.be/UwWGLWp3Nqo
Description of the video:
1. I am placing a webpart on a page (first 404 is because it tries to load items from a list but the list is not selected yet)
2. I am going to edit it but loading the list of lists on the page fails (SitePages in the URL)
3. I am republishing the page with the webpart
4. I am editing the page once again and going to edit the webpart - this time the URL is correct
5. I am selecting a list. React component loads items from this list correctly
6. I am republishing the page and hit F5
7. Again the webpart builds the wrong URL

I used a setup like here:
`protected onInit() : Promise<void>
  {
    sp.setup({
      spfxContext: this.context
    });
    return super.onInit();
  }`

**Comment by koltyakov** [comment]
I have a feeling that you're calling `sp.setup` in the wrong order. `onInit` is async it's better to follow [the samples](https://pnp.github.io/pnpjs/getting-started/#establish-context) more strictly. `this.context` should be passed to `sp.setup` after `super.onInit` is already resolved otherwise part of the context might not be populated yet.
Can you also verify `console.log(this.context.pageContext.web.absoluteUrl)` contains web absolute URL at the time you're calling `sp.setup`? But it's better to establish the context in the same way as the docs suggest to avoid issues which are actually not related to library.

**Comment by AdiuTankT72** [comment]
You are absolutely right. I am not sure know if I missed this .then or used some other example as I can remember that I saw also this version... Nvm thank you very much. Now it is working fine.

**Comment by koltyakov** [comment]
Glad you've figured out and now it works for you. Happy coding!
