### ISSUE TITLE
Issue while searching folder with specific name 

### ISSUE THREAD

**Issue by nmaitreyi** [pnp/pnpjs#1213]
`sp.web.getlists(listname).rootfolder.folder.getbyname(foldername).get().then(data =>{ return data});`

    
We are trying to retrieve a specific folder using name and if folder doesnt exists we need to set a state variable. Unfortunately we are unable to capture the "Folder not found " result as the above code throws error "cannot use then() on undefined"

we need to set a state variable for further processing.
How can we know if a specific folder doesnt exists using pnpjs
 
Any help would be appreciated.

**Comment by koltyakov** [comment]
Hi there,

In your code sample, I can see at least 7 errors, starting with `getlists` which contains 2 mistakes. First, there is no such a method as `getLists`, but `getList`, and secondly, the casing is vital. `getList` and `getlist` are different things. :D Then `getList` expects list server relative URL, but not a name.

So you ended up with something obviously completely incorrect. We'd encourage using typings or, which is even more beneficial, TypeScript, which would immediately highlight that the first method was incorrect when show embed docs for the methods.

```typescript
const processData = console.log;
const handleException = console.error;
const process404Folder = (folderName) =>
  console.log(`Folder doesn't exist ${folderName}`);

const folderName = 'Folder02';

sp.web.getList('/sites/ci/MyLibrary/')
  .rootFolder.folders
  .getByName(folderName)
  .get()
  .then(processData)
  .catch((ex) => {
    if (ex.status === 404) {
      process404Folder(folderName);
      return;
    }
    handleException(ex);
  });
```

![image](https://user-images.githubusercontent.com/7816483/83503175-5df6e780-a4cb-11ea-8d2c-711a28b46d30.png)

**Comment by nmaitreyi** [comment]
Hi @koltyakov , 
Thanks for providing the inputs. Apologies for the typos , as I didn't copy paste the exact code from VS, and typed in directly. 
I am using below code to set the state of a variable in then => which doesn't give desired results always. Is this the wrong way of setting a state variable in then() ?.
Could you please help?
![example](https://user-images.githubusercontent.com/34887983/83525807-2441d300-a503-11ea-805d-a35cb5344d52.PNG)

**Comment by koltyakov** [comment]
This code looks mostly good to me. I'd suggest trying narrowing down the problem in the application.

Chrome SP Editor (or Edge SP Editor) browser extension can be handy to check if the request works for you (just console logging the results). Then when you know that it's not in the API consumption.

Next, React nuances come into play, in React it's important using a correct place for promise-based data retrieval.

If it's SPFx solution, please make sure you're establishing SPFx context ([see more](https://pnp.github.io/pnpjs/getting-started/#establish-context)), otherwise, API calls might go to the wrong base URL and fail somewhere else and not necessarily handled in the App UI.

**Comment by nmaitreyi** [comment]
thank you, this issue got resolved.

**Comment by koltyakov** [comment]
Could you please describe what was a solution? It can be helpful for others if somehow they ended up here on this issue page.
