### ISSUE TITLE
Unable to retrieve quicklinks in IE11 ('Proxy' is undefined).

### ISSUE THREAD

**Issue by nickvanhooydonk** [pnp/pnpjs#1305]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.7 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
Would also like to retrieve the quicklaunch links shown on a modern page in IE11 as well by using an own SPFx webpart.

### Observed Behavior
Got a console error msg 'Unhandled promise rejection ReferenceError: 'Proxy' is undefined' in IE11 when calling:
`sp.web.navigation.quicklaunch()`

### Steps to Reproduce
- Build an SPFx application customizer on version 1.10.
- Include neccesairy @pnp packages (version 2.0.7).
- Include IE11 polyfills (version 2.0.2).
- Replaced all arrow functions by normal ES5 functions.

used following below to test it:
`sp.web.navigation.quicklaunch().then(function(quicklinks: INavNodeInfo[]) {
      console.log('Items!');
    }, function(err:any) {
      console.log(`No Items: ${err}`);
    });`

**Comment by juliemturner** [comment]
If you have not done so please read the documentation on [IE11 Mode](https://pnp.github.io/pnpjs/concepts/ie11-mode/) and our [General Statement on Polyfills](https://pnp.github.io/pnpjs/concepts/polyfill/)

I will add that you don't mention if you've enabled IE11 mode in the setup.... I have often seen that Proxy problem when that isn't set.

Also, in my experience you don't need to replace arrow functions to make it work in IE11 because of TypeScript the code that is running is transpiled to ES5 compatible JavaScript... ergo doing that change for you.

**Comment by nickvanhooydonk** [comment]
Hi @juliemturner ,

Thank you for your quick reply. I totally overlooked the IE11 mode... Sorry.
It works like a charm now!

That said this was more a question than a bug now. Changed it also in the original request for future readers.

And also thanks for the tip on the arrow functions and typescript 👍 
(Deep down I knew this, but I was trying all kinds of stuff when I couldn't get it to work).

Will close this ticket now. You were of great help!
