### ISSUE TITLE
Question:  SharePoint ClientsideWebpart - properties

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1323]
### Category
- [x] Question

### Question
Does anyone know where to find the list of pre-configured properties we can set on all the out of the box SharePoint webparts?

I did do a dump of all 120 webparts on my colletion that were visible in sp.web.getClientsideWebParts().
I found the preConfiguredProperties but that does not define all the properties... unless I made a mistake.

As an example, I was trying to add the Weather webpart to my page and configure it to my current zipcode.
```
part.setProperties<{ location: string }>({
    location: "48326", // and also others like "48326, MI"
});
part.setProperties<{ location: string, unit: string }>({
    location: "48326", // and also others like "48326, MI"
    unit: "c",
});
```

Thanks for any help you can provide!

Here's the link to the guide I used:  [add-controls](https://pnp.github.io/pnpjs/sp/clientside-pages/#add-controls)

```
// create a ClientWebPart instance from the definition
const part = ClientsideWebpart.fromComponentDef(partDef[0]);

// set the properties on the web part. Here for the embed web part we only have to supply an embedCode - in this case a youtube video.
// the structure of the properties varies for each webpart and each version of a webpart, so you will need to ensure you are setting
// the properties correctly
part.setProperties<{ embedCode: string }>({
    embedCode: "https://www.youtube.com/watch?v=IWQFZ7Lx-rg",
});
```

**Comment by patrick-rodgers** [comment]
I am not aware of such a list. It would be hard to track as the properties can change with versions as well. The work to maintain and manage the entire set of interfaces is huge which is why we haven't tried. You might suggest in [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) that they publish a list or make the exported interfaces available somehow in a typings library or something.

Going to close this as answered. If you still have questions please open a new issue, ref this one and provide any additional details possible. Thanks!
