### ISSUE TITLE
items.select().expand() malformed URL

### ISSUE THREAD

**Issue by rouxm** [pnp/pnpjs#1431]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.11]

Please specify what version(s) of SharePoint you are targeting: [SPO and 2013 on Premise]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior (Note: there is no $ before expand)

To retrieve the values of the lookup list. 
(this url was successfully tested on SPO and 2013)

_api/web/lists/getByTitle('PizzaName')/items?$select=Title&expand=lookupfld

### Observed Behavior (note the $ before expand)

This is the generated URL and it fails because of the $ before the expand keyword.

_api/web/lists/getByTitle('PizzaName')/items?$select=Title&$expand=lookupfld

<m:message xml:lang="en-US">The field or property 'lookupfld' does not exist.</m:message>

### Steps to Reproduce

getPizzaOptions(): Observable<any> {
  return 
    web.lists
      .getByTitle('PizzaName')
      .items.select('Title')
      .expand('lookupfld')  //.get() 
}

create a List and name it PizzaName.  Add a few records under Title.

create a second List and name it PizzaOrders. Add column and name it 'lookupfld'.  Give it a type of 'Lookup (information already on this site)' with the following settings;

Get information from 'PizzaName'.
In this column 'Title'
Add a column to show each of these additional fields 'ID'

Once your lists are created, you can retrieve the lookup value with this URL:

_api/web/lists/getByTitle('PizzaName')/items?$select=Title&expand=lookupfld

Regards,

MR

**Comment by juliemturner** [comment]
@rouxm - I'm not sure if I'm going to be able to help you specifically because your example is somewhat abstract, but I can tell you that the library does work fine for lookup field.

I just tested the following code and it worked perfectly:

```TypeScript
const list = await sp.web.lists.getByTitle("PnPList").items.select("Id, Title, MyLookupField/Title").expand("MyLookupField").get();
```
![image](https://user-images.githubusercontent.com/7570936/98058001-aff0c000-1e11-11eb-8e93-67d1cf4184fe.png)

**Comment by koltyakov** [comment]
@rouxm,

Based on your description, sounds you're selecting a lookup value from a wrong list.

- Lists
  - PizzaName
    - Id
    - Title
  - PizzaOrders
    - Id
    - PizzaNameLookup

```typescript
const ordersList = sp.web.lists.getByTitle('PizzaOrders');

const orders = ordersList.items
  .select('Id,PizzaNameLookup/Id,PizzaNameLookup/Title')
  .expand('PizzaNameLookup')
  .get();

console.log('Orders:');
orders.forEach((order) => {
  console.log(` - Order ID: ${order.Id} for Pizza ${order.PizzaNameLookup.Title} (ID: ${order.PizzaNameLookup.Id})`);
});
```

**Comment by patrick-rodgers** [comment]
To be very clear, here are the [official docs showing](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#select-fields-to-return) the "$". I am confused why you considered this a bug? Many folks have successfully used expand through this library.

_This is the generated URL and it fails because of the $ before the expand keyword._

No, it failed because of the error message you received, "The field or property 'lookupfld' does not exist.". When you removed the "$" that query param was simply ignored and no field expansion was done and no error generated.

**Comment by rouxm** [comment]
`When you removed the "$" that query param was simply ignored` 👍

![sp](https://user-images.githubusercontent.com/72996837/98132166-14e7fc80-1e8a-11eb-8146-dc2154e91305.png)
Image showing the problem...

I end up creating a new list (on SOP) with the same attributes and it works.  I don't know what is wrong with the original list but odd that two lists (SOP and 2013 production on premise) would fail in the same way.

Thank you
