### ISSUE TITLE
Extend MSAL auth settings to use stored user credentials for debug and tests

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpjs#1512]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question

Research ways to store user credentials in a secure way to extend MSAL auth for delegated user token to run debug and tests.
Have used https://www.npmjs.com/package/windows-credman but it's complicated by needing to be rebuilt, may have been updated. Also, that would be windows only solution.

**Comment by koltyakov** [comment]
Stanislav's module is a Native one, which requires prerequisites/tooling for building `.cc` otherwise common `npm i` fails. He also did it as a sample long-long time ago, not sure if ever had an intention to maintain a thing.

In my local dev scenarios, I usually use [cpass](https://github.com/koltyakov/cpass) to do not store secrets in a clear text. It's security over obscurity but when an encrypted secret is potentially leaked it's useless until you know the machine key where it was generated.

**Comment by juliemturner** [comment]
Yeah totally open to other options that's the only one I knew of but this sounds great... the goal obviously to allow a user to "configure" their settings file with the details...
