### ISSUE TITLE
getAllChildrenAsOrderedTree doesn't get a new inserted term

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1547]
When I insert a new term under a termset with custom sort order, the term get correctly inserted and is shown at the end of the available terms

Retrieving the terms with 
 const allChannels: IOrderedTermInfo[] = await sp.termStore.sets.getById("d2ded637-78a7-4716-b00b-06f0ff8813bf").getAllChildrenAsOrderedTree();

does not retrieve the newly inserted term, so it looks like it's missing from when retrieving all the terms.

Workaround : Change the custom order for the newly inserted term so it is retrieved

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.13 ]

Please specify what version(s) of SharePoint you are targeting: [ online]

**Comment by patrick-rodgers** [comment]
How quickly are you querying, does it work eventually? Also is my understanding correct:

- Existing term set with custom sort order defined for terms
- Add a new term to this term set
- query using getAllChildrenAsOrderedTree, term does not appear

**Comment by ferrarirosso** [comment]
We have waited at least 30 minutes (customer waited then got in touch with me and I looked at the problem)
Your understanding is correct
I create a term and will look at it in a couple of hours and ping you back

**Comment by patrick-rodgers** [comment]
Thanks, we'll have a look

**Comment by patrick-rodgers** [comment]
Looking at this I am not sure yet how to handle it. A newly created term in a set with custom ordering doesn't have any ordering information associated with it until you go to the custom order screen and make a change to the ordering and click save. The UI apparently has some logic that just puts it at the end of the list. I just confirmed this by following your steps above, seeing that the term is not included, making a change, saving, and the term is correctly included in order.

What is happening in our code is that we grab all the terms and we do get back the new one. BUT when we go to order them it gets dropped because our logic assumes that all terms would have the ordering information associated with them. That is a good assumption IMO as an ordered term _should_ have ordering information :). But that assumption is not true.

We could just append terms to the end, but our logic may differ from whatever the UI does so people may see different results in say a UI written using our method and the UI in the admin section. The solution there is to say that folks need to set the order of all their terms, but that won't always be true.

Are you OK with us including the terms without associated ordering information at the end, understanding they may be in a different order than the admin UI?

**Comment by ferrarirosso** [comment]
I did just wait at least 24 hours, sometimes there are some "magic" timer jobs which fix everything, but that's not the case here.
I think it's a good proposition to append newly inserted terms (without ordering information) at the end so it is ensured that all the terms are retrieved.

Thanks for the quick resolution !
