### ISSUE TITLE
Adding list items: when is listItemEntityTypeFullName required?

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1588]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ latest ]

Please specify what version(s) of SharePoint you are targeting: [all]

### Question
When adding items to SharePoint lists, when is the listItemEntityTypeFullName argument required? I tried both with and without, and I don't see any difference.

`(method) _Items.add(properties?: ITypedHash<any>, listItemEntityTypeFullName?: string)

[edit] I actually found a difference: when using batching, items would only be added if I included listItemEntityTypeFullName. Is this the purpose of the second argument?
`

Thank you!

**Comment by koltyakov** [comment]
In some OData modes, REST need entity type name for adding items (`items.add(...)`).

Internally, PnPjs requests entity type name if not provided. It's also caches it since a couple of releases.

With entity time cached internally now, in most of the cases you won't need getting it separately.

Ahead of time provided value can be needed in the following scenarios:
- Many requests for item creation within the same list will be sent in parallel and no entity type name was cached
- Requests are batched for the server side execution

**Comment by PathToSharePoint** [comment]
Thanks Andrew!
