### ISSUE TITLE
When adding items to sharepoint list using pnp js i get a weird error

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#1608]
Hi,
I have been stuggling , and when i am trying to add an item to sp list , i get this error message
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsers.js:18

Pnp js version     "@pnp/common": "^2.2.0",
    "@pnp/logging": "^2.2.0",
    "@pnp/odata": "^2.2.0",
    "@pnp/sp": "^2.2.0",

I initialized it like this
![image](https://user-images.githubusercontent.com/11780473/108765452-15e58c80-7554-11eb-87b1-264928720c91.png)

using it like this 
```
 const webObject = Web(sitepath);
      debugger;
      const request = invitationReq;
      const iar: any = await webObject.lists
        .getByTitle("testlist")
        .items.add({
          Title:"",     
        });
```

The same code works in chrome, it doenst work in new edge

**Comment by patrick-rodgers** [comment]
That errors is usually related to the parsing logic getting xml or html responses and not knowing what to do with it. The "<" is likely the opening of a tag. Any chance you can look at the full response body? The error should have the raw response attached as [described here](https://pnp.github.io/pnpjs/concepts/error-handling/#reading-the-response). That would probably let us know what the real issue is.

**Comment by harshdamaniahd** [comment]
i can try doing that, but i createda new site and new list and now it works

**Comment by patrick-rodgers** [comment]
We can, certainly seems like a weird thing so was curious. If it happens again let us know and let's try and resolve it. Will go ahead and close this one. Thanks!
