### ISSUE TITLE
Questions about usage of Taxonomy in v2.5.0

### ISSUE THREAD

**Issue by mrebuffet** [pnp/pnpjs#1789]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v 1.3.11 & v 2.5.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question
Hi Team, 

I am looking at upgrading one of our projects currently using the latest v1 (1.3.11) to the latest v2 but I am still facing some limitations when using the new Taxonomy package. Some of those were detailed in this issue (#1160) and have since been addressed but the following 2 questions are still outstanding.

* The first one is about the necessity to know the `TermGroupId` before accessing the term sets and terms with the given examples.  
In the previous object model we could write something [like this (link to v1 documentation)](https://pnp.github.io/pnpjs/v1/sp-taxonomy/docs/term-sets/#terms)  
We are using this technique to load the terms available for a column library and the column definition (`SchemaXML`) does contain a `GroupId` property but the value is always set to empty. It would therefore require an extra call to fetch the `GroupId`.   
      ![image](https://user-images.githubusercontent.com/3445077/120967662-188a8b80-c7ab-11eb-83e1-6c61523ed680.png)   
   Experimenting with the examples, I could find different ways to get around this but I would be hesitant to go down this path if the next version of the API can introduce breaking changes. 

* The second issue I am facing is when I try to access the Enterprise Keywords / search all the terms at the store level.  
The version 1 was using a well known method  in CSOM called `store.GetTerms(labelMachingInfo)`.
Looking at the calls performed by SharePoint Online, this method has now been replaced by this call:   
`POST https://tenant.sharepoint.com/_vti_bin/TaxonomyInternalService.json/GetSuggestions HTTP/1.1`   
   
   I would happily submit a pull request to handle this service call but the fact that the call is marked as "InternalService" might be a blocker here. 

What would be the best course of action to handle those 2 cases using the version 2 of the library?

Many thanks

**Comment by juliemturner** [comment]
@mrebuffet - Unfortunately, the last time we had a chance to review the new beta APIs the ability to get to the store itself wasn't available.  Since then, several endpoints have been added and we can certainly look to enhance our beta coverage, in the mean time you can use the [graph api's more directly](https://docs.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-beta) either through the Graph SDK or though this library by using the getGraph method

`graphGet<T>(GraphQueryable(url));`

**Comment by mrebuffet** [comment]
Thank you @juliemturner 
We have also found some issues with the Graph approach but it does seem that the gap will be a bit smaller at this stage. 
I'll get in touch with the Graph team to hear their suggestion. 
If you are looking for contributors to enhance the beta coverage, I'll be more than happy to help.

**Comment by patrick-rodgers** [comment]
Always looking for help with contributions and would much appreciate the assistance!

**Comment by mrebuffet** [comment]
Quick update.
I have realised that unlike what I originally thought, we can actually get the Termset and its terms without knowing the Term Group Id by making the following calls: 
```
const termSet: ITermSet = await sp.termStore.sets.getById('8109df23-02bb-4f93-86ba-f967bcc62f8f')();

const terms: ITermInfo[] = await sp.termStore.sets.getById('8109df23-02bb-4f93-86ba-f967bcc62f8f').terms();
```
I will submit a PR to add those examples to the documentation. 

We have sent an email to our contacts in the Graph and SharePoint teams to see if we can call this endpoint: 
`https://tenant.sharepoint.com/_vti_bin/TaxonomyInternalService.json/GetSuggestions`
If the answer is positive, I will add the required implementation in a separate PR.

In the meantime, the `getAllChildrenAsOrderedTree` method with caching is good candidate for us to work with.

**Comment by juliemturner** [comment]
@mrebuffet - Thanks for your contribution to the docs it's very much appreciated.

Just wanted to let you know that the endpoint you suggested above:

>https://tenant.sharepoint.com/_vti_bin/TaxonomyInternalService.json/GetSuggestions

is the old way of getting Taxonomy data from the service. Going forward, because of the changes being made to support SharePoint Syntax and other solutions, the engineering team is reworking the managed metadata service and so there are a new set of REST endpoints that will support Taxonomy. What we've already implemented plus some other newer beta endpoints are our target for V2 and beyond ([see statement here](https://pnp.github.io/pnpjs/transition-guide/#drop-client-svc-and-sp-taxonomy-libraries)), ergo we do not want to go back to implementing these old endpoints.

**Comment by mrebuffet** [comment]
Thanks @juliemturner 
I thought it might be the case. 
I didn't find it in the `version-1` branch so I just assumed it was new. 

I have enough ways to work around the current limitations of the Taxonomy API and will wait and see what is released with the new set of REST endpoints. 

Thanks again for your reactivity and the awesome work 🎉
