### ISSUE TITLE
Introduce caching modes for `usingCaching`

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1815]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.6.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

Currently `usingCaching()` offers no mechanism for treating the cache as stale or controlling reading/writing individually. This makes some scenarios where an operation causes the cached value to become stale tricky.

I'd like to propose an addition to `ICachingOptions` which brings it in line with [Request.Cache](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache), or at least introduces the most important modes. Personally I'd consider `refresh` to be the most useful.

This would allow for behaviour such as:

```ts
import { sp } from '@pnp/sp/presets/all';

const items = await sp.web.lists.getByTitle('').items.usingCaching().get();

// let's say user triggers this a couple of seconds after items are fetched()
function onDelete(id) {
  await sp.web.lists.getByTitle('').items.getById(id).delete();

  // use reload to skip reading the cache, force request and then write to cache
  return await sp.web.lists.getByTitle('').items.usingCaching({ mode: 'reload' }).get();
}
```

I will be able to take on a PR that introduces the `reload` mode later this week (hopefully), but I unfortunately will not have time to look at the other modes if these are desired.

**Comment by patrick-rodgers** [comment]
Hey @JakeStanger - This is a great idea, and improving the caching model is something @juliemturner is excited about for v3. I would love to see this idea take root in v3, only because I am not sure the effort is worth it for v2 - but totally up to you. I also think adding this flexibility will be soooo much easier. If you're interested in getting involved in some of the v3 work let us know.

**Comment by juliemturner** [comment]
I'm currently working on what we're calling a "behavior" in v3 to implement a version of pessimistic caching. We have a hurtle to climb because it effectively wants to change the way the pipeline executes while in the middle of execution which is more complicated.  If you want to just make decisions about refreshing, I think that might be able to be handled now.  You can check out the v3 branch, specifically the currently implemented "caching" behavior. You can also see my "theoretical" implementation of pessimistic caching, although realize it currently doesn't work. https://github.com/pnp/pnpjs/tree/version-3/packages/queryable/behaviors

**Comment by JakeStanger** [comment]
I've had a quick look through and the behaviour approach certainly looks like an interesting and flexible way of doing things.

>  If you want to just make decisions about refreshing, I think that might be able to be handled now.

I'm not entirely following here - when you say can be handled now do you mean in v2 or that v3 is in a mature enough state to implement it there?

**Comment by juliemturner** [comment]
I mean that my problem in V3 with creating a behavior for pessimistic caching where I cannot rewrite a method that's already executing -- go figure why that's not possible -- so I suspect you could make a copy or model a behavior off the "caching.ts" file and implement a different behavior that can then be incorporated into V3. Patrick, is I believe just finishing up utterly and completely breaking everything... which is actually exciting... but as soon as it runs again a new caching scheme could be created and tested.

**Comment by patrick-rodgers** [comment]
v3 is in a big state of flux this week as I am in the process of breaking everything :) to rebase the objects to the new model. If you want to contribute (and I hope you do 😀) wait a bit while I get things settled so you can at least test your code.

**Comment by JakeStanger** [comment]
Yeah of course, just give me a heads up when the library is in a more ready state :)

**Comment by patrick-rodgers** [comment]
Going to close this, the v3 branch is stable and would like to see any work on improving caching done there. We've incorporated a lot of past feedback and many of the items mentioned in this thread are already included in the new model. As well it will be much easier to roll your own caching. Thanks!

**Comment by JakeStanger** [comment]
Excellent, I'll have a play when I get some time!
