### ISSUE TITLE
Bug in 2.8.0  /_layouts/15 added 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1869]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version 2.8.0

Please specify what version of the library you are using: [  2.8.0      ]

Please specify what version(s) of SharePoint you are targeting: [  SPO      ]

### Expected / Desired Behavior / Question
`const infos: ITermInfo[] = await sp.termStore.groups.getById(locationsTermGroup).sets.getById(locationsTermSet).children();`
should be 
`https://ecgmcdev.sharepoint.com/_api/v2.1/termstore/groups/39fef54a-4fbf-415f-a6cf-fa13aee87a73/sets/b49f64b3-4722-4336-9a5c-56c326b344d4/children` for my Tenant

### Observed Behavior
But instead it sends:
`https://ecgmcdev.sharepoint.com/_layouts/15/_api/v2.1/termstore/groups/39fef54a-4fbf-415f-a6cf-fa13aee87a73/sets/b49f64b3-4722-4336-9a5c-56c326b344d4/children`
which results in "404 Invalid"
There is <b>"/_layouts/15"</b> that shouldn't be there
once I went back to 2.7.0 it worked correctly

Thank you for a great library

**Comment by patrick-rodgers** [comment]
Have you followed the [guidance on setting up the library](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-setup)? Guessing you tried this in the online dashboard and saw this problem?

**Comment by Ofer-Gal** [comment]
My OnInit did not change when Upgraded to 2.8.0 it is the same as it was the first day I used pnp/js
Should it be different for 2.8.0 ? How does it add "/_layouts/15" to the URL?

`  protected onInit(): Promise<void> {
    return new Promise<void>(
      (resolve: () => void, reject: (error?: any) => void): void => {
        sp.setup({
             spfxContext: this.context
        });
        graph.setup({ spfxContext: this.context });
        Providers.globalProvider = new SharePointProvider(this.context);
        CacheService.config.presence.invalidationPeriod = 300000;
        resolve();
      }
    );
  }`

**Comment by patrick-rodgers** [comment]
Ok, if you are doing that it should be fine - you didn't include that in your initial report so I asked. We will have a look, thanks.

**Comment by patrick-rodgers** [comment]
I can't duplicate this issue - are there any other details you can share? I see you are doing something with a class called "SharePointProvider" - perhaps there is an issue there? If you run the request directly against sp as I have below do you get the correct result?

When I run this code:

```TS
const infos = await sp.termStore.groups.getById("338555a8-3074-4cd9-9432-f72471a14e72").sets.getById("d65d7fca-1b01-4c58-a375-c5aad4a55e55").children();
```

I get the correct url:

`https://{tenant}.sharepoint.com/sites/commsite2/_api/v2.1/termstore/groups/{id}/sets/{id}/children`

**Comment by JakeStanger** [comment]
It's hard to say without more information about how the project is structured, but this could be related to https://github.com/pnp/pnpjs/issues/1621. 

I've found that due to some package-manager oddities, having a dependency rely on one of the `@pnp/sp`'s dependencies (such as `@pnp/odata`), then using `yarn link` on *your* dependency causes some module resolution problems.

Effectively, what seems to happen is the packages get duplicated, which means you end up with multiple instances of the `sp` singleton that aren't properly shared.

Using `yarn list @pnp/sp` or `yarn why @pnp/sp` (or `npm`/`pnpm` equivalents), or even manually exploring `node_modules` might give some indication as to what's happening.
