### ISSUE TITLE
Cannot get all SP group of current user

### ISSUE THREAD

**Issue by silverNM7** [pnp/pnpjs#1892]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.9.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
I want to get the list of all SP groups which the current user is added into.
I added my user account to SP groups in the site. 

### Observed Behavior
For example:
SPGroup1: currentUser
SPGroup2: AADGroup1
AADGroup1: currentUser 

I called `sp.web.currentUser.groups()` in my webpart, but it only returns SPGroup1.
Is there any way I can get SPGroup2 from the result?

**Comment by juliemturner** [comment]
Unfortunately, that is not how the SharePoint API's work with regard to SharePoint groups. This has long been a misunderstanding about how they work and back in the on-premises days I built many solutions to expose the members of an AD group where that group was a member of a SharePoint group. You will have to look the group up using the Microsoft Graph (realizing that you will have to get the needed API endpoints approved to do so) in order to figure this out.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
