### ISSUE TITLE
No way to pass Date() as null on Item Edit

### ISSUE THREAD

**Issue by jtlivio** [pnp/pnpjs#1942]
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

#1940 is not updating dates as null 

```"@pnp/pnpjs": "^2.0.13"```

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of information. Please complete the issue template and supply the relevant details. Thanks!

**Comment by jtlivio** [comment]
Lack of information? This issue have a reference to the discussion of the actual problem, please reopen this is not the proper way to close issues.

**Comment by juliemturner** [comment]
I'm going to effectively just repeat what @koltyakov already suggested in the discussion. I do this rather regularly myself and do not have any problems, so I suspect you have some other problem with your code that is not related to the library.
This works:
```TS
  const nd = new Date();
  const u = await i.update({FieldDate: nd.toISOString()});
  const u = await i.update({FieldDate: null});
```

This code doesn't appear like it would work
`PrintedAt: this.state.certeficatePrintedAt !== null ? this.state.certeficatePrintedAt : null`
based on what I've shared above.  

As @patrick-rodgers suggested your submission is incomplete so it's hard to troubleshoot because you're not providing a complete picture of the problem. For instance, I have no idea what the data type of certificatePrintedAt is... assuming it's a Date then you need to add .toISOString() on the end.  Also, you should verify that PrintedAt is the right name of the field, maybe that's the issue. So, at this point I have little choice but to leave it closed. If you continue to have problems, you could start a new issue and give enough information that we can assist.

**Comment by jtlivio** [comment]
Dear @juliemturner I know the code won't work. I already tried your approach, and other approaches. Your code won't work for me. I tried also to update passing the field and value with JSON but won't work also. I'll open an issue filling the proper template. I'm going to dig the source code also.

Thanks for your reply
