### ISSUE TITLE
Angular 6 - PnPJS - Compilation Errors

### ISSUE THREAD

**Issue by rajendrashekhawat** [pnp/pnpjs#200]
Hi,

I created Angular 6 Project with CLI and added PnPJS as per documentation. Code is not compiling giving all kind of Crypto, Missing Libraries etc.

Please clarify which version of Angular, PnPJS Compatible.

Regards,

**Comment by koltyakov** [comment]
Did you follow https://pnp.github.io/pnpjs/getting-started.html?
Any PnPjs version is compatible with any Angular version as they do not correlate with each other at all.

**Comment by rajendrashekhawat** [comment]
I have followed all the steps. While running the code, it gives all kind of crypto, other library missing errors.

**Comment by koltyakov** [comment]
Can you try running `npm i` in your project? Is the missing dependency included in `package-lock.json`? Install it if it required in the code but missed from node modules. Who knows what happens that you're experiencing missing dependency. Anyway, sounds like a general npm question rather than related to PnPjs.

**Comment by patrick-rodgers** [comment]
Going to close this as there hasn't been an update in a week and this seems like a general question perhaps unrelated to the library. Please do _reopen_ if you believe there is a problem with the pnpjs libraries so we can investigate. Thanks!
