### ISSUE TITLE
page.copy(...) is not working for a page template

### ISSUE THREAD

**Issue by roberAlb** [pnp/pnpjs#2021]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.11.0  ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
When using page.copy(..) I'm expecting to have the same header layout and settings in the page copied

### Observed Behavior
The header is configured to Plain and Show published date to true, when the page is copied the layout is configured to Image and title and show published date appears marked as false.

### Steps to Reproduce
We have a custom template with some configurations and we are using the code .copy(..) to create a page based on that template. After applying the copy function the page is created with the webparts but the settings at the page created are not right.

**Comment by juliemturner** [comment]
Be advised that the pages API that we provide is reverse engineered based on observable calls in the browser console. Microsoft does not provide a supported third-party pages API. As such because features are constantly being released for pages in SharePoint the API is often changing and or new properties are being added and therefore this API can often break and/or not support a new page's feature, which in your scenario is most likely the case as the features you're using we're implemented after this API was developed.  We will add an enhancement request, but this will not be a feature we support in V2 of the library given how close we are to releasing V3 and our intention not to support multiple major versions of the library.

**Comment by roberAlb** [comment]
Thanks for your comment @juliemturner . Do you know more or less when v3 will be released? Thanks.

**Comment by juliemturner** [comment]
Hopefully in the next few weeks we're just trying to finish up documentation.
