### ISSUE TITLE
Cannot fetch installed apps for a team using pnp/graph

### ISSUE THREAD

**Issue by jjsanchez88** [pnp/pnpjs#2024]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0 ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When I try to get installed apps for a existing Team, the property cannot be found

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
graph.teams.getById('5e5ca516-d0d1-4e74-a8b9-cb2606182390').get().then(_team,=> {
            console.log(_team);
            console.log(_team.installedApps);
});

### Submission Guidelines

If we go to documentation, the example says: 

const installedApps = await graph.teams.getById('3531f3fb-f9ee-4f43-982a-6c90d8226528').installedApps.get();

But installedApps thows an error in compilation

Thank you for your feedback!

**Comment by juliemturner** [comment]
Well, this one was a head scratcher.  So, the graph implementation and the corresponding docs were done by someone who is no longer active in the team and is before my time. Apparently, they added docs for this feature but never implemented it, ergo why you're getting an error.  You can easily make this call yourself in the meantime in the following manner, but I'll mark this as an enhancement request so that we get it implemented.

Here's the example I'm referencing - https://docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&tabs=http#example-1-list-installed-apps

```typescript
const apps = await graphGet<{ id: string }[]>(
          GraphQueryable(graph.teams.getById('3531f3fb-f9ee-4f43-982a-6c90d8226528').toUrl(), "installedApps")
        );
```

**Comment by jjsanchez88** [comment]
Thank you so much!!

**Comment by patrick-rodgers** [comment]
Adding the installedApps functionality, will be in 3.2 release. Thanks!
