### ISSUE TITLE
The cache is not invalidated on updates

### ISSUE THREAD

**Issue by nbelyh** [pnp/pnpjs#2028]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

The local cache does not seem to be invalidated when updating items in the list.

I am using pnpjs to get a list of items from a shapepoint list, like this, and using pnpjs **[caching](https://pnp.github.io/pnpjs/odata/caching/)**:
```js
const items = await someList.items.usingCaching().get();
```

Then I modify some item in the same list, like this:
```js
await someList.items.getById(someId).update({ some: changes });
```

Finally, I get the list back again using the first call (i.e. items.usingCaching().get())
The problem is, this call returns the old (cached) version of the modified item, it does not invalidate the cache.
I would expect it to either cancel caching (since the list has been modified) or update local cache on edit accordingly.

Is there a way to reset (clear) local pnpjs cache somehow?
Or this is a bug, and actually the cache should have been updated properly by the library in this scenario?

**Comment by patrick-rodgers** [comment]
This is entirely by design. The caching is not meant to be as complicated as you describe, and we won't be working to add this level of complexity.

The good news is with the upcoming release of v3 it should be much easier for you to introduce any caching scheme you desire.

You can with our caching uses either local or session storage (you can specify) and you can always clear those either directly or using the [storage wrapper](https://pnp.github.io/pnpjs/common/storage/) we include.

**Comment by nbelyh** [comment]
Understood. Thank you for the prompt response! Will adopt my app logic then.
