### ISSUE TITLE
im new to spfx, im facing some problem in pnp people picker(ProcessHttpClientResponseException: Error making HttpClient request in queryable: [400]      at new ProcessHttpClientResponseException

### ISSUE THREAD

**Issue by abekcm20** [pnp/pnpjs#2032]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by abekcm20** [comment]
import { PeoplePicker, PrincipalType } from "@pnp/spfx-controls-react/lib/PeoplePicker";

<PeoplePicker
                      context={this.props.context}
                      titleText=""
                      personSelectionLimit={3}
                      groupName={""}
                      showtooltip={true}
                      //required={true}
                      disabled={false}
                      //onChange={this._getPeoplePickerItems}
                      showHiddenInUI={false}
                      principalTypes={[PrincipalType.User]}
                      resolveDelay={1000}
                      selectedItems={this.getTrainer}
                      //onChange={this.getTrainer}
                      ></PeoplePicker>



pnp.sp.web.lists.getByTitle('Students').items.add({
        StudentName:this.state.StudentName,
        Email:this.state.Email,
        Mobile:this.state.Mobile,
        Address:this.state.Address,
        Referral:this.state.Referral,
        JoinImmediately:this.state.JoinImmediately,
        TrainerId:this.state.Trainer[0],
        Department: {
          '__metadata': { "type": "SP.Taxonomy.TaxonomyFieldValue" },
          'Label': this.state.Department[0].name,
          'TermGuid': this.state.Department[0].key,
          'WssId': '-1'
        }
      }).then(response =>{
        alert('Adding an item has been completd Successfully');
      });

    }

**Comment by juliemturner** [comment]
Ok, so I'm going to close this issue because your edited title suggests that you're having problems with the PnP People picker, this is the PnPjs library repository not the one for the pnp controls, that would be [@pnp/spfx-controls-react](https://github.com/pnp/sp-dev-fx-controls-react).  But also, some advice so that when you post your issue to that repository you can get expedient assistance. 

It's really important, especially if you're new that you take the time to fill out the issue template completely. Even if this was the right repo I wouldn't have nearly enough information or clarity to help you. That's why we create the issue templates, so please take the time to fill them out as completely as you can and if you accidentally submit without finishing you can edit your submission you don't have to create a new response.

![image](https://user-images.githubusercontent.com/7570936/152034021-8ae51bb1-22ad-4414-9746-429bbc0993d3.png)
