### ISSUE TITLE
File / Listitem version information, load column updates for each version

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2083]
### Category
- [X ] Question

### Expected / Desired Behavior / Question
Is there an API available that can return the changed columns for each version? The default version page shows this information:
https://XXX.sharepoint.com/sites/2021-0130/_layouts/15/Versions.aspx?FileName=%2Fsites%2F2021%2D0130%2FShared%20Documents%2FGeneral%2FXXX.docx&IsDlg=1

![image](https://user-images.githubusercontent.com/126084/154080146-18f1f34b-eeec-43f7-b76c-2eee3c1580e4.png)

**Comment by juliemturner** [comment]
Yes, I'm not sure why it's not documented but this should work to list versions:

```TypeScript
const version = await sp.web.lists.getByTitle("PnPList").items.getById(2).versions();
```
and you can get a specific version as well, check out the official docs [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/listitem_list_versions?view=odsp-graph-online).

**Comment by mdissel** [comment]
I'm aware of that function, but that only returns the main version information. I need the updated / column information for each individual version (loading in a single request)

**Comment by juliemturner** [comment]
Yes, that is why I said you can get a specific version as well. Right below `List Versions` is `Get Version` and from the docs anyway, show that fields can be included... https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/listitemversion_get?view=odsp-graph-online

I'm sorry I really don't have time to test this right now, but based on what I can see that call would be something like

```TypeScript
const version = await sp.web.lists.getByTitle("PnPList").items.getById(2).versions.getById(1).select("fields").expand("fields");
```
But you'll have to play around with it.

**Comment by mdissel** [comment]
I've tested this, but no fields are returned:

`const versions = await file.versions.select("CreatedBy","Fields").expand("CreatedBy", "Fields").get();`

**Comment by patrick-rodgers** [comment]
The method used to generate the page you shared a screen shot above is not available through the API. It is being done with async processes on the server side to load up all that information for the versions. There is no endpoint in SPO that will just give you the edited fields.

The link Julie shared above is for the graph and doing a quick test in graph explorer I do get back the field information for a call like:

`https://graph.microsoft.com/v1.0/sites/{site id}/lists/{list id}/items/1/versions`

We don't currently have support for all the SharePoint related calls in the graph library because they are generally covered in the sp lib. Right now we don't even have support to get a site by id. I'll add that which will enable this call in the next version:

```TS
import "@pnp/graph/sites";
import { Site } from "@pnp/graph/sites";

// getById will be in the next version
const sites = graph.sites.getById("{site id}");

const users = await Site(sites, "lists/{listid}/items/{item id}/versions")();
```

Longer term we are discussing what to keep in sp/add to graph. This is a good example of where graph has functionality sp does not.
