### ISSUE TITLE
How to migrate V2 MsalClient & SPHttpClient usage to V3?

### ISSUE THREAD

**Issue by trueleader** [pnp/pnpjs#2092]
### Category
- Question

### Version
Please specify what version of the library you are using: 3.0
Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
I have problems to solve some of the multiple hundred problems of our project.
*Besides the opinionated ugly looking anonym function calls (changing `... .usingCaching().get()` to `... .using(Caching())()`) and many documentation still containing V2 content*

In V2 we imported MsalClient and SPHttpClient
```typescript
import { MsalClient } from "@pnp/msaljsclient";
import { sp, SPHttpClient } from "@pnp/sp";
```

we used them to implement some helper functions for things not (yet) possible within the library/SP Rest API.
How such things must be now implemend, after the clients were replaced by behaviors?

e.g.
```typescript
/**
 *
 * setting a group as owner of a group is not possible with REST Api:
 * @see https://github.com/pnp/pnpjs/issues/957#issuecomment-565484501
 */
async function setGroupOwner(groupId: number, ownerGroupId: number): Promise<void>
{
	const [site, web] = await Promise.all([sp.site.select("Id").usingCaching().get(), sp.web.usingCaching().select("Url").get()]);

	const endpoint = `${web.Url}/_vti_bin/client.svc/ProcessQuery`;
	const body = `<Request AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="15.0.0.0" ApplicationName="Javascript Library" xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009">
		<Actions>
			<SetProperty Id="1" ObjectPathId="2" Name="Owner">
				<Parameter ObjectPathId="3" />
			</SetProperty>
			<Method Id="4" ObjectPathId="2" Name="Update" />
		</Actions>
		<ObjectPaths>
			<Identity Id="2" Name="740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${site.Id}:g:${groupId}" />
			<Identity Id="3" Name="740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${site.Id}:g:${ownerGroupId}" />
		</ObjectPaths>
	</Request>`;

	const client = new SPHttpClient();
	const response = await client.post(endpoint, { headers: { "Content-Type": "text/xml" }, body });
	const result = await response.json();
	if (!result || !result.length)
		throw new Error(`Invalid server response when setting owner of group '${groupId}'`);
	if (result[0].ErrorInfo)
		throw new Error(`Server error response when setting owner of group '${groupId}'`);
}
```

e.g.
```typescript
async function setSensitivityLabel(clientId: string, driveId: string, docId: string, labelId: string): Promise<void>
{
	const web = await sp.web.select("Url").usingCaching().get();

	const endpoint = `${web.Url}/_api/v2.1/drives/${driveId}/items/${docId}/setSensitivityLabel`;
	const data = {
		id: labelId,
		justificationText: "Added by GremlinApp",
		assignmentMethod: "standard"
	};

	const result = await msalFetch(clientId, endpoint, data, "POST") as { id: string };
	if (result.id != labelId)
		throw new Error("Label ID of API response did not match request");
}

/*
 * implementations  for helper functions used above
 */
async function msalFetch(clientId: string, endpoint: string, data: unknown, method: string|undefined = "GET"): Promise<unknown>
{
	const msal = await getMsal(clientId);
	const response = await msal.fetch(endpoint, {
		method,
		headers:{ "Content-Type": "application/json", "Accept": "application/json;odata=nometadata" },
		body: JSON.stringify(data)
	});

	return await ensureNonErrorResult(response) as { id: string };
}

const msals: { [name: string]: MsalClient } = {};
async function getMsal(clientId: string): Promise<MsalClient>
{
	let msal = msals[clientId];
	if (!msal)
	{
		const web = await sp.web.select("Url").usingCaching().get();
		const hostname = new URL(web.Url).hostname;
		msals[clientId] = msal = new MsalClient(
			{
				auth: {
					authority: `https://login.microsoftonline.com/${hostname.replace(".sharepoint.", ".onmicrosoft.")}/`,
					clientId,
					redirectUri: location.href
				}
			},
			[`https://${hostname}/AllSites.Write`]
		);
	}

	return msal;
}

async function ensureNonErrorResult(response: Response): Promise<unknown>
{
	if (response.ok)
	{
		try { return await response.json(); }
		catch (_) { throw new Error("Invalid API response"); }
	}

	let errorMessage;
	try
	{
		const errorResult = await response.json();
		errorMessage = errorResult.error?.message;
	}
	catch (_)
	{
		// nothing: errorMessage is defaulted on use
	}

	throw new Error(errorMessage || "Invalid API error response");
}
```

**Comment by juliemturner** [comment]
First, let me state that by opening with ~

>Besides the opinionated ugly looking anonym function calls (changing ... .usingCaching().get() to ... .using(Caching())()) and many documentation still containing V2 content

~ doesn't really put anyone here who *volunteers* their time in a mental position to want to help you. And I might suggest that you consider that this isn't a great way to interact with the community.

Putting that aside, let me address that statement.
1. I'm sorry that you think that our new behaviors syntax is ugly, but I can't see how it can be called 'opinionated'. By moving to this new underlying pattern, we feel we've advanced the library significantly and we did work very hard to minimally impact those trying to migrate but of course, this is a major version, and we knew some change would be necessary... seem to me though that this is a fairly easy search and replace operation for the most part.
2. We worked VERY hard on documentation, completely reorganizing it and trying very hard to get everything updated to v3. Given again, that this is a community effort, it would be SIGNIFICANTLY more productive if you could submit an issue outlining where we missed updating the docs or, even better yet, submit a PR making the appropriate corrections.
3. Also, regarding all the changes you have to make I think you might want to consider a "config" file that you can define in your project that will set up the necessary factory interfaces that you can then import into the various areas of your code where you need to use them, thereby making "sp" the new object vs the v2 global object by just adding a simple import the config file. This can also help you because it simplifies having to do all the selective imports everywhere you use the object, by consolidating them into one configuration file.  I'll be submitting a sample project later this week, I am delayed because again, not my day job, and also, I needed to wait for 1.14 of SPFx to drop before I can update everything. So to explain more:

If there's a file called pnpConfig.ts that contains:
```TypeScript
import { WebPartContext } from "@microsoft/sp-webpart-base";

// import pnp and pnp logging system
import { spfi, SPFI, SPFx } from "@pnp/sp";
import { LogLevel, PnPLogging } from "@pnp/logging";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";

var _sp: SPFI = null;

export const getSP = (context?: WebPartContext): SPFI => {
  if (_sp === null && context != null) {
    //You must add the @pnp/logging package to include the PnPLogging behavior it is no longer a peer dependency
    // The LogLevel set's at what level a message will be written to the console
    _sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));
  }
  return _sp;
};
```

Then in your initialization code (assuming SPFx here but not necessary):
```TypeScript
import { getSP } from './pnpjsConfig';

protected async onInit(): Promise<void> {
    this._environmentMessage = this._getEnvironmentMessage();

    super.onInit();

    //Initialize our _sp object that we can then use in other packages without having to pass around the context.
    //  Check out pnpjsConfig.ts for an example of a project setup file.
    getSP(this.context);
}
```

And then, in any file that needs to use the sp instance, reference it as such (obviously this is pseudocode as the references would need to be addressed):
```TypeScript
import { getSP } from './pnpjsConfig';
let sp = getSP();
```

Ok, now that I've addressed that bit, your other question is about utilizing the MSAL client in v3. Since I'm still not exactly clear on what environment you're in exactly I'm just going to point you to the updated V3 documentation on [Authentication](https://pnp.github.io/pnpjs/concepts/authentication/).  Maybe if this doesn't meet your needs you can suggest ways that we can improve it and/or submit a PR to address our shortcomings.

**Comment by patrick-rodgers** [comment]
@juliemturner is a much more patient person than I am.

**Comment by trueleader** [comment]
@juliemturner Please don´t misunderstand the intention of the sentence:
> Besides the opinionated ugly looking anonym function calls (changing ... .usingCaching().get() to ... .using(Caching())()) and many documentation still containing V2 content

I will add two comments - this one unrelated to the original question so it can be marked as offtopic

The sentence should be only somewhat of a site-note unrelated to the question - it shouldn´t be a opener for a discussion inside this thread. I appologize for the created confusion and I did not mean to attack the work you are doing. I use the library because it has a much more complete list of helpers than the own and the usage is more consistent
Italic seems to be the wrong way to mark the sentence "smaller"

The oppinion is my one and maybe I´m alone: If I get a code for review purposes and don´t know the used library ... I would not know what the intention of the second parenthesis would be. My workaround for V3 is to split the expression:
```
const listItemsRetrievalQuery = ... .using(Caching());
const result = await listItemsRetrievalQuery();
```

About the documentation: A new consumer of the library can´t know if the documentation is V2 or V3. As the navigation relative early hints the transition to V3, each user may assume, that the whole documentation is V3.
When spot-checking the documentation of the sp package, most starts with `import { sp } from "@pnp/sp";`. So I think it is not yet updated:
- https://github.com/pnp/pnpjs/blob/main/docs/sp/site-users.md
- https://github.com/pnp/pnpjs/blob/main/docs/sp/permissions.md
- https://github.com/pnp/pnpjs/blob/main/docs/sp/lists.md
- https://github.com/pnp/pnpjs/blob/main/docs/sp/items.md
- https://github.com/pnp/pnpjs/blob/main/docs/sp/attachments.md

**Comment by trueleader** [comment]
The solution I try to migrate is a pure spfx app. It is added via SharePoint app catalog and the user can only do things given by his SharePoint permissions. e.g.: If the app is called it checks the corresponding structure of the SharePoint lists and if it does not match the expectation it shows an "update needed" dialog. If the user is a SharePoint SiteCollection-Admin, the dialog contains the update possibility itself, which may add new fields, indexes and other stuff.
Another user only "contributes" to the data: showing data aggregated form list items, adding new ones, uploading files which gets AIP labels and so on

My migration started with a search&replace too, but as the library moves away from the global object I try it too: The WebPart creates the SPFI and injects it into a service. The service is the central accessor of the SharePoint so implementations of React-Components, Redux stores and BusinessLogic does not need to know how/where to read and write data.
So inside the service/helpers I only need to replace `sp.` with `this._sp.`. And then migrating caching, batching, etc. 

**But the initial question concerns the things inside the code-blocks above:**
There is no SP REST API which allows setting a "SP security group" as owner of another "SP security group". So we use the SPHttpClient to call the SOAP endpoint `/_vti_bin/client.svc/ProcessQuery` in behalf of the user. 
The behaviors require that we have a SPFI instance, inject the behavior and then continue using methods on the SPFI. But SPFI does not know about thes SOAP endpoint... so our implementation of helpers which should add functionality which pnpjs not yet has seems to be catched in itself.

Maybe I neet to create a Custom Request Client but I am not sure: I think this part of documentation is V2 not V3 too:
https://pnp.github.io/pnpjs/sp/custom-irequestclient/

**Comment by juliemturner** [comment]
Yes, it does appear that all the documentation has left the `import { sp } from "@pnp/sp";` and it bears rethinking, although how to remove it isn't entirely obvious to me at this moment as it's going to create a situation where a lot of code would need to be duplicated... kindof a mess... the thinking is probably that as long as you have an instance of the spfi, and you call it sp that code works (although the import is totally misleading), you have to have the sp that we document elsewhere.... I'll discuss this more with @patrick-rodgers and see if we can come up with a better way to document that in all the packages.  Thank you for that feedback.

It does appear `custom-irequestclient` didn't get deleted and should have, the replacement for that is to write your own `behavior` instead, this is because we noted in the transition docs that the entire base code for the library was rewritten from scratch and so how you implement a custom request pipeline would be different and we consider that an advanced scenario.  I would check out the documentation on [Behaviors](https://pnp.github.io/pnpjs/core/behaviors/) but you might want to go farther and read all the docs on [Timelines -> Moments](https://pnp.github.io/pnpjs/core/timeline/) as well so that you can understand how the underpinnings of the library have fundamentally changed.

My guess is in the end you're going to want to write something similar to the [SPFx behavior](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/behaviors/spfx.ts) replacing DefaultHeaders, DefaultInit, DefaultParse, etc (maybe not all of those and maybe not just those) with ones that meet the needs of making a SOAP call... Then using my former pnpjsConfig make a getSPSOAP function to get an instance of a sp object specifically configured with your SOAP behaviors.

**Comment by trueleader** [comment]
Thank you for your answer. 

I already read the Timelines & Moments pages - but it is something which must be read and tried multiple times, before all implications will be clear :) I wasn´t sure if it is the right starting point, but your answer pointed to the same as my initial thoughts.
I will git it a try and post the solution. As this will take a while I moved the V3 upgrade to another branch and first fix/change some other stuff

**Comment by tavikukko** [comment]
Hi all,
SP Editor uses CSOM XML in some of its functionalities. Now migrating it to V3

This sample is run at PnPJS Console V3, not published yet.

This works, I can call sp rest api and also SOAP endpoints. Just wondering am I doing it right and also is using spPost method ok?

```typescript
import {
  DefaultHeaders,
  DefaultInit,
  RequestDigest,
  Web,
  spfi,
  spPost,
} from "@pnp/sp/presets/all";

import {
  BrowserFetchWithRetry,
  DefaultParse,
  Queryable,
} from "./@pnp/queryable";

import { TimelinePipe } from "./@pnp/core";

(async () => {

  function SPSoapHandler(): TimelinePipe<Queryable> {
    return (instance: Queryable) => {
      instance.using(
        DefaultHeaders(),
        DefaultInit(),
        BrowserFetchWithRetry(),
        DefaultParse(),
        RequestDigest());

      // fix url for SOAP call
      instance.on.pre.prepend(async (url, init, result) => {
        if (url.indexOf('/_vti_bin/client.svc/ProcessQuery')) {
          url = url.replace(/_api.*_vti_bin/, '_vti_bin')
        }
        return [url, init, result];
      });
      return instance;
    };
  }

  const webid = (window as any)._spPageContextInfo.webId
  const siteid = (window as any)._spPageContextInfo.siteId

  /* context */
  const ctx = await (window as any).moduleLoaderPromise || (window as any)._spPageContextInfo
  const sp = spfi(ctx.webAbsoluteUrl || ctx.context._pageContext._web.absoluteUrl)
    .using(SPSoapHandler())

  // get web title
  const web = await sp.web.select("Title")()
  console.log("Web Title: ", web.Title);

  var payload = `
            <Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="SPEditor">
              <Actions>
                <Method Name="SetFieldValue" Id="9" ObjectPathId="4">
                  <Parameters>
                    <Parameter Type="String">kissa</Parameter>
                    <Parameter Type="String">tarxas</Parameter>
                  </Parameters>
                </Method>
                <Method Name="Update" Id="10" ObjectPathId="2" />
              </Actions>
              <ObjectPaths>
                <Identity Id="2" Name="740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${siteid.slice(1, -1)}:web:${webid.slice(1, -1)}" />
                <Property Id="4" ParentId="2" Name="AllProperties" />
              </ObjectPaths>
            </Request>`;

  // update webproperty
  const res = await spPost(Web(sp.web, `/_vti_bin/client.svc/ProcessQuery`), { body: payload });
  console.log(res)

})().catch(console.log)
```

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by trueleader** [comment]
As I try to keep the solution simular to library behavior, this is my:

```typescript
interface IProcessQueryResult
{
	ErrorInfo: string|null;
}

class ProcessQuery extends Queryable<Array<IProcessQueryResult>>
{
	private _body = "";

	constructor(base: SPInit)
	{
		super(base, "_vti_bin/client.svc/ProcessQuery");

		// DefaultHeaders() injects application/json headers which cannot be overwritten on execute time
		this.using(InjectHeaders({ "Content-Type": "text/xml" }));
	}

	public body(requestXml: string): this
	{
		this._body = requestXml;
		return this;
	}

	protected execute(userInit: RequestInit): Promise<void>
	{
		if (!this.body.length)
			throw new Error("request body not set");

		return super.execute({ ...userInit, method: "POST", body: this._body });
	}
}


declare module "@pnp/sp/fi"
{
	interface SPFI
	{
		readonly processQuery: ProcessQuery;
	}
}

Reflect.defineProperty(
	SPFI.prototype,
	"processQuery",
	{
		configurable: true,
		enumerable: true,
		get: function (this: SPFI)
		{
			return new ProcessQuery(this._root);
		}
	}
);
```

Using via:
```typescript
function doSomeProcessQuerySuff(sp: SPFI)
{
	const body = `<Request SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="Javascript Library" xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009">...</Request>`;

	const query = sp.processQuery.body(body);
	const result = await query();
	// ...
}
```
