### ISSUE TITLE
Getting all Events of a Group during a specified date range?

### ISSUE THREAD

**Issue by Sluuuush** [pnp/pnpjs#2095]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.0.1    ]

Please specify what version(s) of SharePoint you are targeting: [    Sharepoint Online     ]

### Expected / Desired Behavior / Question
Im new to pnpjs and need to get all Events of a Group Calendar during a specified date range with @pnp/graph.
When using  *const events = await graph.groups.getById('21aaf779-f6d8-40bd-88c2-4a03f456ee82').events();*  I won't get recurring events and need to filter afterwards. 

To get all Events i'm using * const events = await graph.groups.getById(groupId).getCalendarView(new Date('2022-01-01'), new Date('2022-04-01'));*  
This works fine, but im limited to the 10 reults from an API Call to graph. So i have to use 'top' to get more results. But for groups.getCalenderView 'top' doesn't exist.

Am i missing something? Not an experienced user!

### Observed Behavior

For CalendarView of Users the top and select functions are available. 
*const view2 = await graph.users.getById('user@tenant.onmicrosoft.com').calendarView("2020-01-01", "2020-03-01").select("start").top(15)();*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Thank you for your feedback!

**Comment by juliemturner** [comment]
To get recurring events you need to get an event and then [check for instances](https://pnp.github.io/pnpjs/graph/calendars/#get-event-instances).  We theoretically support that (because it's broken in v3.0.1) but I was just working on it and could not get instances to return any results although now the call executes properly.

The event itself will have [recurrence](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) property if it's a recurring event. And then you can theoretically get [Event Instances](https://docs.microsoft.com/en-us/graph/api/event-list-instances?view=graph-rest-1.0&tabs=http).... but like I said I'm not getting it to work for me... if you wait until Tuesday when 3.0.2 drops I can tell you at least the call will work properly when you pass the dates to it, but I'm not sure if you'll have any better luck.

**Comment by juliemturner** [comment]
Finally got back around to this and realized that I had a bug in my test code and that this is, in fact working so I'm going to close the issue as resolved.
