### ISSUE TITLE
Implement usingCaching for search fluent API

### ISSUE THREAD

**Issue by SpliceVW** [pnp/pnpjs#211]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.1.4]

### Expected / Desired Behavior / Question

Many of the PNP JS functions allow for the chained `usingCaching`. Although search has an internal caching layer, this is useful for reducing server roundtrips. Given the utility of search for producing rollups, `usingCaching` would be similarly beneficial for the fluent search API.

**Comment by patrick-rodgers** [comment]
The big issue here is we don't do caching currently for any non-get requests. This is because anything else is usually an action that changes something. For search this isn't true, BUT does mean we need a way to carve out a flag or something to allow caching non-get requests. Will see what this takes to implement, but can't promise we will add it. Def get what you mean though, thanks for the idea!

**Comment by SpliceVW** [comment]
Yessir, works beautifully and now I've got a nice, snappy interface! Thanks for the fast response.
