### ISSUE TITLE
How to determine if an object is inheriting permissions from an ancestor?

### ISSUE THREAD

**Issue by pheidler** [pnp/pnpjs#2173]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.6  ]

Please specify what version(s) of SharePoint you are targeting: [  365 ]

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

I am trying to determine whether an object (List item) inherits permissions from its containing subsite. Initially, I tried using [firstUniqueAncestorSecurableObject()](https://pnp.github.io/pnpjs/sp/permissions/#first-unique-ancestor-securable-object), however, this function always return the object itself, even if the permissions page in Sharepoint indicated that the object is inheriting permissions from an ancestor (in this case, the subsite). 
![image](https://user-images.githubusercontent.com/43651586/159551184-93db73a8-b275-4b20-950d-275b7a7ac44f.png)

Is there something I'm missing about the intended use of this function? 

As a workaround, I thought it might be possible to compare [role assignments](https://pnp.github.io/pnpjs/sp/security/#role-assignments) for each object. I was able to do this successfully elsewhere in my SPFx app when determining if a subsite inherits permissions from its parent site by simply comparing the role assignment objects, but the role assignments appear to be different when comparing between a list item and a subsite. 

Let me know if you have any advice. Thank you!

**Comment by patrick-rodgers** [comment]
Looking at the [official docs](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/jj171634(v=office.15)#remarks) it seems like it should work as you expect.

> If role assignments are defined directly on the current object, the FirstUniqueAncestorSecurableObject property returns the current object. Otherwise, the property returns the object from which role assignments are inherited.

So digging in a bit further I tested it and always get back whatever the thing itself is - and looking at the url it makes sense - we aren't appending `FirstUniqueAncestorSecurableObject` to the path! So that is a bug and we'll get it fixed up. Sorry about that.

What is a bit interesting is that this is also been broken in v2, so either you are the first to use this method in our library - or lots of folks out there will suddenly be confused at the next release as to why behaviors may have changed.

**Comment by pheidler** [comment]
Awesome, glad you caught that. Sure, I can take a look at it. 

Thanks!
