### ISSUE TITLE
Angular 12 + MSAL outside SharePoint

### ISSUE THREAD

**Issue by nicholasp** [pnp/pnpjs#2192]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   v2 or v3    ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

### Question
I have an Azure Web App with Angular 12 and Angular MSAL. I setup successfully the App registrations with necessary API permissions for SharePoint and Graph and I can do from client side api calls to both graph and direct sharepoint api. The angular msal interceptor handles the bearer token for the calls. I would like to know if it is possible to use pnpjs library instead of custom writing all the url calls.

**Comment by juliemturner** [comment]
I think this is the documentation you're looking for, although this is for V3... 

https://pnp.github.io/pnpjs/concepts/authentication/#msal-in-browser

**Comment by nicholasp** [comment]
Thanks for the answer. I tried browser with msal but one problem is that msal triggers 2 times one from my angular msal and one from the pnp. It seems like angular interceptor doesn't trigger from pnp http request. Also I got weird errors either at vscode before compile or at runtime and I was fixing them with like:
 removing
`import { spfi, SPBrowser } from '@pnp/sp';`
and adding
`import { spfi, SPBrowser } from '@pnp/sp/presets/all';`

I tried successfully a request with:
```
const sp = spfi('https://masoutis.sharepoint.com/sites/ExpressTeam').using(
      SPBrowser(),MSAL(configuration, authParams)
    );

    await sp.web.lists
      .getByTitle('ScheduleList')
      .items.getPaged()
      .then((r) => {
        console.log('sp.web', r);
      });
```

but something is missing. for example after .items the only methods is: getItemByStringId, getById, getPaged
if i use any others i got errors like
`Property 'getAll' does not exist on type 'IItems'`

my final imports after some test was
```
import { spfi, SPBrowser, Fields, IFields } from '@pnp/sp/presets/all';
import { MSAL } from '@pnp/msaljsclient';
import { IList } from '@pnp/sp/lists';
import '@pnp/sp/webs';
```

**Comment by juliemturner** [comment]
I can't really offer any guidance on the architecture of your app regarding how Angular is behaving. If you set up MSAL auth in Angular then yeah, I would suspect 2 calls will be made because when configured to use MSAL, PnPjs will make calls to get a token. If you already have a token from some other process then you could bypass our auth step and write your own [behavior](https://pnp.github.io/pnpjs/core/behaviors) that retrieves the token from some other source. 
>If it were me, I would look at the [MSAL function](https://github.com/pnp/pnpjs/blob/version-3/packages/msaljsclient/index.ts) and then write my own code for the action that sets the Authorization header.

With regard to your "weird errors" with VSCode it feels like you're talking about typing issues and given that you're attempting to use the /presets/all import I suspect you might want to review the documentation on [selective imports](https://pnp.github.io/pnpjs/concepts/selective-imports/) so that you can better grok how we've segmented our code to provide the best experience for the bundle size... i.e selective imports mean that you only import the modules from the library that you are going to use.  So, in other words, you need to make sure you add the appropriate imports. The above would probably (I didn't take the time to actually test my answer) be done like:

```TypeScript

import { spfi, SPBrowser } from "@pnp/sp";
import { MSAL } from "@pnp/msaljsclient";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const sp = spfi('https://masoutis.sharepoint.com/sites/ExpressTeam').using(
  SPBrowser(),MSAL(configuration, authParams)
);

await sp.web.lists
    .getByTitle('ScheduleList')
    .items.getPaged()
    .then((r) => {
      console.log('sp.web', r);
    });
```

**Comment by nicholasp** [comment]
thanks you very much! your answers help me a lot. I took behavior from docs example an the code looks like this:

```
public sp(url: string = environment.sharepointUrl): SPFI {
    return spfi(url).using(SPBrowser(), this.GetMSALTokenForPNP());
 }

public GetMSALTokenForPNP(): TimelinePipe<Queryable> {
return (instance: Queryable) => {
      instance.on.pre(async (url, init, result) => {
        const scopes = this.getScopesForEndpoint(url);
        const account = this.msalService.getAllAccounts()[0];
        let token = '';

        await this.msalService
          .acquireTokenSilent({ scopes, account })
          .pipe(
            .... etc
          )
          .toPromise();

        init.headers = { ...init.headers, authorization: `Bearer ${token}` };

        return [url, init, result];
      });

      return instance;
    };
}
```

seems it works. if you have any comments or suggestions, please, let m know.
🙏

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
