### ISSUE TITLE
Adding List Item Comments returns a proxy rather than ICommentInfo or IComment

### ISSUE THREAD

**Issue by jchilde** [pnp/pnpjs#2194]
Adding a list item comment using:

`return await list.items.getById(itemId).comments.add(newComment as any);`

actually returns a proxy rather than evaluating to a ICommentInfo.

The comment does get added; however, it doesn't return the comment data.

**Comment by aaademosu** [comment]
That is the expected behavior. From the proxy object returned you will have access to properties and functions exposed by the IComment interface. 
I can get the id of the comment added and other details from the object returned. 
![image](https://user-images.githubusercontent.com/2017630/161352613-a3d814ee-5bba-4048-97b8-72e643a663e3.png)

**Comment by jchilde** [comment]
Then the documentation needs to be changed to reflect that the object returned is something other than the interface listed.

Jeffrey A. Childers
________________________________

**Comment by juliemturner** [comment]
What you see in the browser console is a proxy object, which is "typed" as IComment... IComment is the typing, so the documentation is correct.

i.e. 

```TypeScript
const commentInfo = await list.items.getById(itemId).comments.add(newComment as any);
console.log(commentInfo.id);
```
Will transpile because the result is typed properly as IComment...

FYI, ICommentInfo is the type for the object you should be passing to the add method, so really this would be more accurate:

```TypeScript
const newComment: ICommentInfo = {....};
const commentInfo = await list.items.getById(itemId).comments.add(newComment);
```
Looks like that's reflected in the [docs](https://pnp.github.io/pnpjs/sp/comments-likes/#add-comment) but certainly if you find anything you think should be different you can open up a new issue or submit a PR.
