### ISSUE TITLE
Remove external identity from a specific file 

### ISSUE THREAD

**Issue by AmitFidler** [pnp/pnpjs#2227]
### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [   
  "@pnp/nodejs-commonjs": "^2.13.0",
    "@pnp/sp-commonjs": "^2.13.0"        ]

Please specify what version(s) of SharePoint you are targeting: [    Microsoft 365     ]

I was trying to work with the latest release but it does not support the typescript version I am using - 4.6.2

### Expected / Desired Behavior / Question
I am trying to remove an external user from a sharing link,
saw the reference in this issue - while I'm trying to remove the access from a particular file and not from the siteUsers. 
https://github.com/pnp/pnpjs/issues/1185.

### Observed Behavior
My intention is to remove the external use access from a particular file and not from the site itself.
I was trying to get a listItem role assigments members:

        const listItemRoleAssignments: IListInfo = await listItem
            .select('RoleAssignments')
            .expand('RoleAssignments/Member', 'RoleAssignments/RoleDefinitionBindings')
            .get();
 
 then target a role assigment for a sharpeoint group that holds the relevant sharing links. 

from that group I used to get the group by Id and then delete the email of the external member from the asset which worked great: 
            
`sp.web.siteGroups.getById(GROUP_ID).users.getByEmail(EMAIL).delete();
`
This now fails and I get this error even trough there is an external user that has access to the link.

:\"Error making HttpClient request in queryable [404] Not Found ::> {\\\"odata.error\\\":{\\\"code\\\":\\\"-1, Microsoft.SharePoint.Client.ResourceNotFoundException\\\",\\\"message\\\":{\\\"lang\\\":\\\"en-US\\\",\\\"value\\\":\\\"User cannot be found.\\\"}}}\""

couldn't find any changes on sharepoint side that would fail this one.

**Comment by juliemturner** [comment]
>I was trying to work with the latest release, but it does not support the typescript version I am using - 4.6.2

Version 2 is less able to support TypeScript 4 than Version 3 is, and I can't imagine that there's any reason you can't use TypeScript 4.6.2 with Version 3 which is built with TypeScript 4.5.5

After that I'm not sure I can help you as I don't really understand the problem. You have some code that did work and now doesn't? What changed?

**Comment by AmitFidler** [comment]
Hi @juliemturner thanks for the quick response! 
About the typescript versions, my bad, it wasn't typescript version but node versions. 
I saw on the documentation pnp v3 only supports node 12 while we work on node 14 and that was my problem over there,
Is there suppose to be support for node 14.x version in the near future?  

But sticking to the main issue, I am trying to get and remove a particular member of a Sharepoint group, 
in this case a "sharing link" group which consists of the users who have access to the link. 

I am getting inconsistent results, and in some cases while trying to list the group members I get an empty array. 
`using this function - sp.web.siteGroups.getById(GROUP_ID).users. 
`
and when I do find a user and manage to delete it without getting a 404 using this:
`sp.web.siteGroups.getById(GROUP_ID).users.getByEmail(EMAIL).delete();
`
The user does not actually get removed - and still have access. 

It may be my possible lack of understanding of this groups and sharing link mechanism, 
but please if you can, let me know if this is a sharepoint api expected behaviour or an inner pnp handling of this list group members which is filtering some of the members for some reason.

Thank you so much! 
pnp is for sure a great tool which helped us a lot :)

**Comment by juliemturner** [comment]
I'm sorry I'm confused... our documentation (for V3) indicates we support Node14 and higher (Minimal Requirements)[https://pnp.github.io/pnpjs/getting-started/#minimal-requirements]. I use Node 14 (because that's the max version of NodeJS supported currently by SPFx) and I believe @patrick-rodgers uses Node 16.  Again, V2 is going to have less support for higher versions of NodeJS.

With regards to your specific issue, I'm not sure I can promise you my time to research the issue other than to say this library does a pass through of the SharePoint APIs (there are exceptions, but they are very rare) and it sounds like there isn't a bug simply they are not behaving as they should which we can't really do anything about. I did check the endpoints your outlined above and they are basic calls. You can check the outcome by looking at the browsers network tab to see the call being made and the payload returned. If the payload returned (in the browser tab) is different than the outcome you're getting via the PnPjs call or differ from SharePoint documentation, then you may have indeed found a bug and we would welcome you posting those details for us to investigate further.
 
Otherwise, the best way to get your issue addressed would be to create a test project that does the raw SharePoint API calls that you're attempting (again you can get them from the network tab) and then submit an issue to the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) repo where the Microsoft engineering team can address it.

**Comment by AmitFidler** [comment]
Hi @juliemturner thanks a lot for the detailed response, 
I understood from my explorations that when trying to remove an external identity from a link, internal and external users are treated differently, and the focus should be using the shareLink with identities to remove and not actually processing the group members which is consistent for internal/external users. 

I re created this by using msal-node and doing the http calls that mimics that ui as you suggested, this is for sure not a pnp issue but a strange sharepoint issue that has a workaround, supporting the share link api might be useful for future versions :) 

Thanks!
