### ISSUE TITLE
Assigning permissions to M365-group

### ISSUE THREAD

**Issue by Leif-Frederiksen** [pnp/pnpjs#2246]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.13]

Please specify what version(s) of SharePoint you are targeting: SPO         ]

I need to assign permissions to a Microsoft-365 group – not a SharePoint group or individual user.
I can get the group id, but this is a string, not a numerical value as required by roleAssignments.add() method.
How can I accomplish this?

**Comment by juliemturner** [comment]
If I understand the question correctly, I think what you're missing is the conjunction of SharePoint permissions and Microsoft 365 groups... The role assignments belong to the SP so in order to add a M365 group to SP you need to first create the SP User to represent that AAD group and then add that SP User to a role assignment... I think in general people use [ensure user](https://pnp.github.io/pnpjs/sp/webs/#ensureuser) to create that SP user from the group.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
