### ISSUE TITLE
Timeout After 30 Minutes - "The security validation for this page is invalid and might be corrupted"

### ISSUE THREAD

**Issue by LastGunslinger** [pnp/pnpjs#2304]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.14.0]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When setting up an SPFI object using the method shown in the documentation below, the context is invalidated after 30 minutes. Any POST requests after that time result in an HTTP 403 error - "The security validation for this page is invalid and might be corrupted". This was not an issue in v2 of the library, and I believe, but am not sure, that it was even working correctly in early versions of v3. This should constitute a bug and not just a breaking change between versions 2 and 3, since this is entirely separate behavior, even taking into account the fact that there is no longer a global sp object.

### Observed Behavior
The app context is timed out and the user has to refresh the page to clear the error.

### Steps to Reproduce
Create an app using PnPJS v3.2.0 and set up an SPFI object using this code from the documentation. If the user leaves the SP page for more than 30 minutes, they will receive the error when returning.

I'm opening this issue because I believe issue #2186, which refers to the same problem, was closed in error. It was noted in that issue that this problem was corrected in version 3.2.0, but I am still able to reproduce it in 3.2.0. There is a [workaround](https://github.com/pnp/pnpjs/issues/2186#issuecomment-1118366195) proposed in that ticket, but a workaround is not a solution. If there is no plan to fix this issue and the workaround is the only solution that will be provided, please update the v3 documentation to reflect this, since users who were already using v2 will have this issue when they migrate.

```javascript
const sp = spfi().using(SPFx(this.context))
```

**Comment by juliemturner** [comment]
#2188 is the PR that fixed the issue, so I'm assuming you're referencing the issue referenced #2186. Assuming yes, then no, the issue was not closed in error. The "workaround" that person "proposed" would have absolutely nothing to do with the token not being refreshed as that is just a different way to do the same thing... so why it is ok for them when doing it that way I can't say as there isn't enough code to even begin to speculate. 

If you are experiencing an issue, please share a sample in a cloneable repository that demonstrates how you've architected your solution so that we can try and validate where the problem is, and we'll attempt to assist you.

**Comment by LastGunslinger** [comment]
@juliemturner - [Here is a link](https://github.com/LastGunslinger/pnpjs-repro-2304) to the the repo where I have reproduced this error. After doing more testing in a limited environment, I can consistently reproduce the error when using the `sp.utility.resolvePrincipal` function in the `@pnp/sp/sputilities` module. When that function is called, I can see an HTTP request to _https://<my-sp-site>/_api/SP.Utilities.Utility.ResolvePrincipalInCurrentContext_, which initially returns a 200 response, but returns a 403 after the 30 minute timeout.

In the linked repository, the main branch reproduces the issue, while the version2 branch does essentially the same thing, just using v2 of the PnPJS library. The rest of the code is just a standard web part scaffolded using the Yeoman generator as described [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part). I only made some slight changes to allow using React hooks.

**Comment by bcameron1231** [comment]
Hi @LastGunslinger  Thank you for adding the repository. I am going to pick up this issue and I will work on your repro and hope to have some information back to you tonight or tomorrow. Appreciate the patience.

**Comment by bcameron1231** [comment]
@LastGunslinger Quick update for you.

I have reproduced the formsDigest timeout behavior using your main branch in your repository (Thank you!). I have isolated the issue to a specific area of code where the PnPjs _SPFx behavior_ is grabbing legacyPageContext digest value with a new expiration, instead of creating a new one.

This issue only occurs when the spfi() object and spfx behavior is instantiated multiple times during the lifecycle of a web part. 

**Our recommendation** is to create your spfi() object once and re-use it in your application. i.g, In a global scope such as the init method of your Web Part and pass that down to your components. In your code, you pass down the entire WebPartContext and you are re-creating the spfi() object inside your hook, which means it's constantly being re-created. Doing so is not a design pattern we recommend, and we will be adding better documentation around this.

Additionally I personally think you may want to re-consider passing an entire WebPartContext object around in your solution where possible.

---------------------------------------------
We do believe this could be classified as bug and we are working address this issue. We have a planned release for Friday and hope to have a fix in place. 

However, my recommendation to address this issue is to not create your spfi() object in your hook, but to instead create it in a global place such as your init() and pass it down to your functional component for re-use in your hooks.

**Comment by LastGunslinger** [comment]
@bcameron1231 Thanks for getting back with me so quickly! I'll definitely try out your suggested solution by creating only one instance of the SPFI object and re-using it. In your opinion, would this scenario work?

1. Create an SPFI object in the init() function of the web part
2. Pass that object to the parent app component on render and store it as global state (most likely using React Context)
3. Reference that global state directly in sub-components as opposed to passing it down as a prop

I'm asking because I'm trying to avoid re-architecting my existing applications to add the SPFI object as a prop to all of them.

**Comment by bcameron1231** [comment]
Hi! Yes, this would work to put it on a Provider Context, and a pattern I have done in the past!

The only thing I'd probably mention, unrelated to this specific issue is as you develop your solution out, be very cognizant of how you are using your Contexts. They are great for sharing across components, but they also greatly reduce re-usability of components as you'll always need that context provider wrapping your children components.

Imagine a scenario where you want to move all of your hooks into a re-usable library for all of your future customizations, you've now made a hard dependency on your components which use that hook, to be a consumer of a context. Where as if you were passing as a prop, it enforces that dependency without bringing in any extra context values which may be unrelated to the new component you're building.

Does that make sense?

**Comment by LastGunslinger** [comment]
@bcameron1231 Thanks for the feedback and clarification on SPFx() vs. SPBrowser(), I really appreciate it.

I also appreciate the advice on using contexts. In our applications we've abstracted our component logic into hooks, and it's the hooks that depend on the context, but I understand your point and it is valid. For our use cases, a bit of coupling is generally acceptable, mainly because it's generally understood that these components won't be used outside of SharePoint (we're the SharePoint team, and the only team currently using React), and PnPJS is used in just about every single one of our apps, since interacting with SharePoint is their main goal. I can see how this could be a hindrance though, especially if we were to branch out.
