### ISSUE TITLE
Nodejs environment uncaught error

### ISSUE THREAD

**Issue by SuperioOne** [pnp/pnpjs#2356]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.5.1 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
Failed requests should not cause uncaught error.

### Observed Behavior
If an observer throws error, timeline execute can emit and catch the error successfully but for some reason same error exists at the end of callstack and causes uncaught error.

NodeJs v16-17-18 force exits, v14 works but prints warning about uncaught error.

### Steps to Reproduce
/debug/launch/sp.ts
```typescript
export async function Example(settings: ITestingSettings)
{
  const sp = spSetup(settings);

  try
  {
    // Deliberately fail query with either invalid parameters or behavior.
    await sp.web.expand("__~~").select("__~~")();
  }
  catch (err)
  {
    // It will catch and print error normally.
    console.log(err.name);
  }

  // add force wait to callstack
  await (new Promise<void>((resolve, _) => setTimeout(() => resolve(), 5000)));

  // Or you can invoke another query
  // const info = await sp.web();

  // at this point, process exits with uncaught error

  Logger.log({
    level: LogLevel.Info,
    message: "This message won't be printed",
  });

  process.exit(0);
}
```
You can also reproduce same issue with custom behavior throwing an error.
```typescript
export function ErrorBehavior()
{
  return (instance: any) =>
  {
    instance.on.pre.prepend(async function (this: any, url: string, init: RequestInit, result: unknown)
    {
      instance.log(`Interrupting timeline.`, LogLevel.Verbose);
      throw new Error("Intentional Error.");

      return [url, init, result];
    });

    return instance;
  };
};
```

**Comment by patrick-rodgers** [comment]
You can catch this in your app so it doesn't crash:

```TS
(<any>process).on("unhandledRejection", (...args: any[]) => {

  console.log("unhandledRejection: " + args[0].stack);
});
```

I encountered this while working on the Cancelable behavior but haven't been able to pin it down. Node is exiting as they made a change in how they want to behave.

When you said the same error exists - what I saw was that it was the same error but from a different location - based on the promise ref numbers. Currently not sure where this issue exists, my worry is that it may be somewhat out of our control due to how awaiting works + the event loop. But, this is something we will continue to research. Great if anyone can share additional details.

**Comment by patrick-rodgers** [comment]
I just merged the fix for this problem, it will be available in the [next nightly build](https://pnp.github.io/pnpjs/concepts/nightly-builds/) if you want to test it out.

**Comment by SuperioOne** [comment]
Thanks for the fix, nightly build works perfectly!
