### ISSUE TITLE
pnpjs publish page with comments get error

### ISSUE THREAD

**Issue by kongmengfei** [pnp/pnpjs#2412]
I am using pnpjs to publish a site page but get the below error:

`let iFile = this.sp.web.getFileById(uniqueId);
await iFile.publish(comment ?? '');
`

-------
Request URL: https://abc.sharepoint.com/sites/VitalQA/Announcements/_api/web/getFileById('77d1c1c5-6b0e-4775-befd-086925e5bb02')/publish(comment='%24a%20-split%20%22%20-%20%22%0A%0A%2Fsites%2FVitalQA%2F_layouts%2F15%2Fguestaccess.aspx%3Fe%3Dpb')
Request Method: POST
Status Code: 400 
------
![image](https://user-images.githubusercontent.com/57654821/192251779-07905c98-c543-49c2-bc49-f0282821baf7.png)

I guess there might be some limitations regarding the comment. Can you help me?

### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version
the latest pnpjs version
nodejs 14.18.2

**Comment by juliemturner** [comment]
I'm not sure that you can do what you're trying to do as that wouldn't be supported because the results of `getFileById` would be a file not a client-side page.

See documentation on loading a client-side page: https://pnp.github.io/pnpjs/sp/clientside-pages/#load-pages
and then the second part of this example is about adding a comment to a client-side page: https://pnp.github.io/pnpjs/sp/comments-likes/#add-comment

**Comment by patrick-rodgers** [comment]
Have you tried it with a comment like "test comment"? The one example you shared seems to show an encoded file path in the comment.

**Comment by patrick-rodgers** [comment]
This looks like a test case you made up failing. If you want to work on it and submit a PR to address it, please do, but this isn't something we are likely to invest time in researching. We'll leave the issue open in case anyone else has some time.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
