### ISSUE TITLE
Renamed field blank after changing browser language

### ISSUE THREAD

**Issue by jd215** [pnp/pnpjs#2422]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.7.0  ]

Please specify what version(s) of SharePoint you are targeting: [  SP Online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When I create  a list and rename the Title field, I expect it to stay the same when I change the language (to Dutch, in MS Edge browser)

### Observed Behavior
The Title field appears blank when I restart the browser after changing the language

### Steps to Reproduce
1 Make sure the browser language is set to English
2 Run this code

```
const list = await sp.web.lists.ensure("New list");
await sp.web.lists.getById(list.data.Id).fields.getByInternalNameOrTitle("Title").update({ 
      Title: "NewTitle"
    });
```

3 Change browser language (to Dutch) and restartthe browser

4 Check the Title field in the list settings: it appears blank

When I tried the same using an existing list, this issue did not occur.

Thank you for your feedback!

**Comment by juliemturner** [comment]
So correct me if I misunderstand, you're saying if you create the list through the UI this doesn't happen?

**Comment by jd215** [comment]
That's correct. Small nuance: opening the list settings shows different field labels than the views

Existing list: shows correct label ('NewTitle') in list settings, shows incorrect label ('Title') in the view

New list: show incorrect label ('') in list settings, shows incorrect label ('LinkTitle') in the view
```

//existing
   await sp.web.lists.getByTitle("Existing list").fields.getByInternalNameOrTitle("Title").update({ 
      Title: "NewTitle"
    });
//new
    const list = await sp.web.lists.ensure("New list 2"); 
    await sp.web.lists.getById(list.data.Id).fields.getByInternalNameOrTitle("Title").update({ 
      Title: "NewTitle"
    });
```

**Comment by juliemturner** [comment]
Ok, well unfortunately I don't believe this has anything to do directly with PnPjs but it probably has to do with the extra work the client-side UI does for you when creating a new list above and beyond the very minimalist ensure method. I never use it personally when I'm creating a list, I would instead create the list and then create the fields etc etc... not sure if that would make a different in what you're seeing or not, but just saying.

Unfortunately, I personally don't have the cycles right now to research what is going on under the covers but if I were going to take the time, I'd inspect the existing list that is working to see what is different about the field values that might help point to what would fix things.  Specifically, I would want to look at the SchemaXml property of the field that has things like DisplayName etc... that might shed some light.  A quick way to inspect is to use a browser (where you're already authenticated into the tenant) and then put right in the address bar the url for the rest endpoint... like:

`https://{yourtenant}.sharepoint.com/sites/{yoursite}/_api/web/Lists/GetByTitle('Existing List')/fields`

Then if you copy/paste that into VSC you can format it and inspect how it might be different. Also inspect the new list you created and see how it's different. 

Otherwise maybe someone else already knows the answer.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
