### ISSUE TITLE
pnp js version[ "@pnp/sp": "^3.6.0"] : items.add using hooks error:"The security validation for this page is invalid and might be corrupted"

### ISSUE THREAD

**Issue by kandharithirumalreddy** [pnp/pnpjs#2424]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: ["@pnp/sp": "^3.6.0" ]

Please specify what version(s) of SharePoint you are targeting: [ SPFx1.15.0]

### Expected / Desired Behavior / Question
Add items should work as well as get

### Observed Behavior
With version 3 there is no longer sp.setup(this.context); in the onInit() of the *WebPart.ts file of SPFx
When using hooks now I am passing the context: WebPartContext as props to the components.

So all my gets work fine with const sp = spfi(window.location.origin + "/sites/dpc").using(SPFx(context));

But when I try to add, I am getting the error you get when there is no RequestDigest
Error: "The security validation for this page is invalid and might be corrupted"

#_Originally posted by @github-actions[bot] in https://github.com/pnp/pnpjs/issues/2102#issuecomment-1119715472_

**Comment by bcameron1231** [comment]
A couple notes I want to add.

Don't pass around the context like this and try not to initiate context multiple times. We should initialize PnPjs once, and then gain access to the SPFI object in the child components using getSP(). Passing around context through props is extremely difficult to test and should be avoided (and can have some unintended consequences with PnPjs). 

In your example, it looks like you may be passing the context because you want to initialize a new sp context from a different site than where the web part is running because you want to pull/add data to another Site (correct me if I'm wrong). If you want access into another web you should use the AssignFrom as outlined in the transition guide [here ](https://pnp.github.io/pnpjs/transition-guide/#assignfrom-and-copyfrom)

**In your root web part .ts file**
```
getSP(this.context);
```

**In your component or hooks**
```
//Get access to SPFI object using 
const _sp:SPFI = getSP();

//Access another site
const web = spfi("yourUrl").using(AssignFrom(_sp.web));

//Make call to get or update data
web.lists.getByTitle("Documents").items.getById(1).update({Title: "New Title"})
```

Here is a sample I put together for you. This is using Custom Hooks (not native React hooks) but the code is the same. Initialize once, get access to spfi context, reassign it to a new web instance. You'll find that code in the useDocuments hook

https://github.com/bcameron1231/sp-dev-fx-webparts/tree/custom-hooks-dynamic-passed-in-web
