### ISSUE TITLE
batch caching on user group not working

### ISSUE THREAD

**Issue by kongmengfei** [pnp/pnpjs#2457]
I am using batch caching to fetch current user's group + list items:

```
 const [batchedWeb, execute] = this.sp.site.rootWeb.batched();
 batchedWeb.using(Caching());
 let allFGapprovers = [];

// item request
 batchedWeb.lists.getByTitle(this._listTitle).items.filter('...some filters')
            .select("Id", "ApproversId", "Title")().then(r => allFGapprovers = r.map(x => x['ApproversId']));

 let userGroups = [];

// user group request
 batchedWeb.currentUser.groups().then(g => userGroups = g.map(x => x['Id']));

 await execute();
```
The items request is always working, but the user group request is not working. the first request will return normal data but subsequent requests will always return an empty array. 

First Request: 
![image](https://user-images.githubusercontent.com/57654821/198926136-e31ae579-b88f-49d0-94ea-6a2e85c9c191.png)

subsequent request:
![image](https://user-images.githubusercontent.com/57654821/198926106-e62656ce-d675-41e6-85e4-d9af7b2d93c4.png)

does not know if it's a bug or if I am doing something wrong. please help me!

### Category
- [ ] Enhancement
- [x ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version
PS > node -v
v14.20.0
spfx: 1.15.2
"@pnp/sp": "^3.7.0"

**Comment by patrick-rodgers** [comment]
Had a quick look, def a bug. BUT - if you reverse the order of your code and do the group request first you get those values and not the items. Meaning it doesn't have anything to do with the type of request (I don't think) rather something with the timing in resolving batches that have no requests due to caching. I'll add a test to catch this once I figure out what is happening.
