### ISSUE TITLE
getitem returns proxy object

### ISSUE THREAD

**Issue by manuhinCCS** [pnp/pnpjs#2480]
Hi,

File uploaded using pnp version 3 and trying find the out id of newly uploaded file using getitem but proxy object retuned.
![image](https://user-images.githubusercontent.com/112081775/203111876-50f2c0e4-9e21-43f9-ab6c-e85800c8f8cb.png)

### Category
- [x] Bug

### Version

"@pnp/sp": "^3.7.0"
node - 14.20.0

### Expected / Desired Behavior / Question
It should return the details of current uploaded file.

### Observed Behavior
Returns proxy object.
![image](https://user-images.githubusercontent.com/112081775/203110945-68da043a-6eec-44fb-8b39-12ca780732a4.png)

Thank you.

**Comment by patrick-rodgers** [comment]
This is correct. The [getItem method](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/folders/types.ts#L123) has to make a request to the server no matter what so we can correctly ref the item. Since we are making that request we also load the item data and merge it into the IItem. So the item properties should also be there. i.e. fileResponse.Title should be valid. If you expand the Proxy/Target you should see the fields.

**Comment by manuhinCCS** [comment]
Then how can i get the id from the response for further processing.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by manuhinCCS** [comment]
Response required.
fileResponse['ID'] Is this a right way?
