### ISSUE TITLE
PNP Search Failed with Status 500

### ISSUE THREAD

**Issue by aman-sharma24** [pnp/pnpjs#2481]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [ 3.8.0 ]

Please specify what version(s) of SharePoint you are targeting: [ 1.15.0 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Expected to get matching Sharepoint Search Results from the api

### Observed Behavior
API Search Failed with Status 500

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*
 /api/search/postquery
(I am using the API to get matching results to that text query with filters)
![pnpIssue](https://user-images.githubusercontent.com/84671380/203124727-00c2f4dd-3919-4c52-b19a-2d919fe2489d.PNG)

**Comment by juliemturner** [comment]
We pass through the results of the request... a 500 error is an internal server error and wouldn't be related to the library but to the SharePoint REST service itself.

**Comment by Vertamin** [comment]
This suddenly and randomly started happening to me too on two unrelated Tenants. Same project, without any changes lately.

The thing is it has something to do with the Tenant, because the files tab on SharePoint upper search bar is crashing too. I opened a ticket with Microsoft, lets see if they know something.

![Error 1](https://user-images.githubusercontent.com/69040799/203718207-3b160267-c941-48c5-b9f1-fde32e4050dd.PNG)
![Error 2](https://user-images.githubusercontent.com/69040799/203718216-b73ce38f-c62c-4945-8e66-fc296417ed26.PNG)

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
