### ISSUE TITLE
[CancelablePromise] p.cancel is not a function

### ISSUE THREAD

**Issue by AndreiYefimau** [pnp/pnpjs#2507]
Copy/paste code sample from https://pnp.github.io/pnpjs/queryable/behaviors/#cancelable to empty solution causes an error 
![image](https://user-images.githubusercontent.com/102244472/207584440-e214a538-2494-4c58-bc5a-b2796c5923c7.png)

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.9.0 ]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Promise cancels the request

### Observed Behavior
Unexpected error occured

### Steps to Reproduce
Create empty solution / install all dependencies
Copy/paste sample code

**Comment by patrick-rodgers** [comment]
Interesting, the behavior here appears to have changed again. Because of all the awaits/promises/async activity across all the behaviors our code that was:

```
return this.execute().finally()
```

no longer held the cancel reference, but changing it back to:

```
const p = this.execute()

p.finally(..)

return p;
```

Appears to have fixed the issue. Will PR an update so you can try out the nightly build. Because this is still considered beta we won't push an emergency release. Thanks for letting us know!
