### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'web')

### ISSUE THREAD

**Issue by abhishek0205** [pnp/pnpjs#2524]
I am getting this error while making a POST call, with GET it works fine. 
Below is the simple code that is throwing this error.

import { spfi, SPFx } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const sp = spfi(
      "SiteUrl"
    ).using(SPFx(this.context));

    const iar: IItemAddResult = await sp.web.lists.getByTitle("Sample").items.add({
      Title: "Title",
      Description: "Description"
    });

**Comment by juliemturner** [comment]
At first glance this seems fine, assuming the line that defines the sp const is right before the line that calls the add method. I will state that get calls always work if they're running in the context of the page, because get calls don't require an auth token. POST calls however, do, and if for whatever reason the sp object isn't configured it doesn't have a token you can get issues.  If you provide a more complete example, we can maybe help you more. 

Also, you removed the issue template, ergo not filling in details. So, I'm also commenting not really knowing what version of the library you're using, which would change my answer.

**Comment by juliemturner** [comment]
So as best I can tell from the above, you're using React Hooks, yes? If that's the case then I suspect you're having the same issue others have had in the structure of how you're using PnPjs inside of the effects. @bcameron1231 has some [guidance](https://github.com/pnp/pnpjs/issues/2304#issuecomment-1149911244) as he's our resident expert on that topic, he also created a [sample project](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-hooks).

**Comment by abhishek0205** [comment]
I tried the approch mentioned in the sample project. It throws the below error now and the webpart breaks.
Its basically breaking in the get call...

code: -----
const spCache = spfi(_sp).using(Caching({ store: "session" }));

    spCache.web.lists
      .getByTitle("Checklist")
      .items()

error:--------
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Reflect.has called on non-object

**Comment by patrick-rodgers** [comment]
If you take the calls out of all the React code and just run them, are they working as expected?

**Comment by abhishek0205** [comment]
I tried the other sample solution i.e. "react-pnp-js-sample" and it worked. Thanks for your help

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
