### ISSUE TITLE
onInit:  sp.setup question (in v2)

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2553]
### Category
- [x] Question
### Version

Please specify what version of the library you are using: [   2.14   ]
I'm unable to upgrade to v3 at this point but hopefully someone can answer a question....

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

### Expected / Desired Behavior / Question

I have used pnpjs to fetch lots of things like lists, items etc.... and never had to add this to onInit:
```javascript
    sp.setup({
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      spfxContext: this.context as any
    });
```

However, I recently tried to use sp.search and it does seem to require it or I get a 403 error.

My question is what types of operations require it?  Is it only search?  or graph or what?
Just curious to understand.

Thank you

**Comment by juliemturner** [comment]
Because the spfxContext property is typed as an "any" in pnpjs, as it should be, we don't hard couple to the SharePoint framework by taking the dependency needed to type it.  The fact that you have to disable a eslint rule is because you have eslint rules. If you don't want to have to do that then you need to disable the associated rule.

**Comment by mikezimm** [comment]
@juliemturner ,
Maybe I am mis-understanding, but my question was not related to typing spfxContext as 'any'.

What I was wondering, is which parts of the pnpjs  library require the entire sp.setup function to be there.

In my case, I was able to fetch subsites, lists, libraries, pages, and items without any of those 4 lines in the onInit.

**Comment by juliemturner** [comment]
In version 2, you must establish the sp object with the setup method for any of the sp.xxx methods to work. It's a global variable, so you only need to do it once for your entire project, but it needs to be done. Similarly, to use any of the graph.xxx methods you need to do graph.setup. 

So, honestly your question doesn't make sense. You need to do it for all methods to work. It doesn't have to be done in the onInit, that's just the best practices location to do it since you don't want to run into a situation where you're trying to make a call but haven't set up the global object yet.

**Comment by mikezimm** [comment]
> In version 2, you must establish the sp object with the setup method for any of the sp.xxx methods to work. It's a global variable, so you only need to do it once for your entire project, but it needs to be done. Similarly, to use any of the graph.xxx methods you need to do graph.setup.
> 
> So, honestly your question doesn't make sense. You need to do it for all methods to work. It doesn't have to be done in the onInit, that's just the best practices location to do it since you don't want to run into a situation where you're trying to make a call but haven't set up the global object yet.

Ok thank you for the reply.  I will double check and see if I have it somehow loaded elsewhere in the project.
