### ISSUE TITLE
3.12.0 Access is denied error

### ISSUE THREAD

**Issue by datyin** [pnp/pnpjs#2570]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
@pnp/sp: 3.12.0
@microsoft/sp-*: 1.16.1

### Observed Behavior
Updating list item, getting termStore groups throws error "Access is denied. (Expection from HRESULT)". This happens only on latest version, 3.11.0 works fine.

### Steps to Reproduce
await sp.termStore.groups() < access error
await item.update(...) < access error
..etc

**Comment by patrick-rodgers** [comment]
OK, we were worried about this as discussed in #2552. To address the requirement for a token in the newer v2.1 apis we added in code to always add the token to all SPFx requests. If the SharePoint application from which we get the token (the default SPFx one) doesn't have the required permissions, it looks like that is considered before the legacy cookie authentication. So you are getting access denied because the application does not have the required scopes.

We will get a 3.12.1 release out backing out this change, but long-term you should be [requesting the necessary permissions](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests) for the SP Application.
