### ISSUE TITLE
Get and set privacy policy of user profil data

### ISSUE THREAD

**Issue by RoSchoe** [pnp/pnpjs#2598]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Question:
Is there a way to get or set the privacy policy with current pnpjs for the current user?
Like: https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms583766(v=office.14)

Maybe with:
- @pnp/graph/users
- @pnp/sp/profiles

We want that the user can switch from everybody to private.

**Comment by patrick-rodgers** [comment]
I am not sure this is possible online. The docs you link are for SP 2010. I believe you can still do it through the SP admin center, but unaware of an API to do this.

**Comment by bcameron1231** [comment]
Agree with Patrick. This is not possible. Please see the purple section in the linked documentation below. You cannot create or change these properties that used to be available as part of Microsoft.Office.Server.UserProfiles because they are read only from the client APIs


https://learn.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint#apis-for-working-with-user-profiles-in-sharepoint

**Comment by RoSchoe** [comment]
Thank you for the information - then we will have to find another way.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
