### ISSUE TITLE
[groupSiteManager] Doc link missing / content update proposal

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/pnpjs#2653]
### Category

- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.14.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

Following release of version 3.14.0, the `groupSiteManager` node documentation page should be available in the navigation.

In addition, I would like to update the documentation page, to precise that the code contains more info regarding available methods and that there's a generic `call` method available to call any other one from the `_api/groupsitemanager` endpoint, just like it's proposed in the `sp-admin` node.

### Observed Behavior

The `groupSiteManager` node documentation page isn't showed up in the navigation and is only available through the search bar.

### Steps to Reproduce

N/A

**Comment by bcameron1231** [comment]
Hi @michaelmaillot  Thanks for raise of the issue! We'd love the update to the navigation for groupsitemanager, let me know if that's something you want to tackle, or for us to do.

As for the call() function, we've actually discussed this internally and are already planning on adding a separate section to the docs just for this functionality, as it applies to any endpoint. It will be fixed in this issue #2639

**Comment by michaelmaillot** [comment]
Thanks for clariying this info about `call` method, good to know that it will be globally available / documented 😊

I will provide a PR for the navigation / doc in code update if it's ok for you.
