### ISSUE TITLE
file exists()  returns false when library has more than 5000 files

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2707]
### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.15.0      ]

Please specify what version(s) of SharePoint you are targeting: [ SPO        ]

### Expected / Desired Behavior / Question
When using statement such as 
```
const exists: boolean = await projWeb.getFolderByServerRelativePath("DPCDocuments").files.getByUrl(fixFileName).exists();
```
Should return true when the file exists

### Observed Behavior
In libraries having more than 5000 files, the function always returns False

Is there another way to find out if the file exists?

Thank you

**Comment by patrick-rodgers** [comment]
Not sure, what information do you have to work with? If you have an absolute url I guess you could hit it directly, but if you just have the name that obviously won't work.

**Comment by Ofer-Gal** [comment]
The example you have in https://pnp.github.io/pnpjs/sp/files/#exists
Shows just file name and so I did.
Should it be absolute URL relative?

**Comment by patrick-rodgers** [comment]
I more meant what information do you have at the time you want to know if a file exists? Just the name? You'd have too I suppose the site url and know which library it is in, right?

**Comment by Ofer-Gal** [comment]
Sure,
 ```
// Get a Web object for all the other functions based on the projectNumber's Team Site
const theWeb = (projectNumber: string): IWeb => {
    const sp: SPFI = getSP();
    const spAppSite: SPFI = spfi(window.location.origin + "/Teams/" + projectNumber).using(AssignFrom(sp.web));
    return spAppSite.web;
};
```
then later
```
const projWeb: IWeb = theWeb(projectNumber);  
```
then
```
const exists: boolean = await projWeb.getFolderByServerRelativePath("DPCDocuments").files.getByUrl(fixFileName).exists();
```
projWeb points to the site and  "DPCDocuments" is the document library. How can I be more specific than that?

When the exists is false, the next action is to upload the document, but then it errors that the file already exists. (Catch 22 😰? )

Why does it work fine for smaller libraries?

**Comment by bcameron1231** [comment]
The issue lies in here (in bold)... 
const exists: boolean = await projWeb.getFolderByServerRelativePath("DPCDocuments").**files**.getByUrl(fixFileName).exists();

Making this request, SharePoint is querying the files, which, which more than 5k, SharePoint will throw the error. 

You can be more precise if you already know the path (which looks like you do), is to bypass the folder & files calls, and get access directly to the file itself.

`const exists: boolean = await projWeb.getFileByServerRelativePath("/sites/contoso/Shared Documents/Document.docx").exists();`

`const exists: boolean =  await fileFromServerRelativePath(this.sp.web, "/sites/contoso/Shared Documents/Document.docx").exists();`

**Comment by Ofer-Gal** [comment]
I did not know you can do that but hey it works like a charm.
Maybe it should be added as another variation in the documentation.

Thank you very much
