### ISSUE TITLE
`file.addChunked` fails due to URL length limit

### ISSUE THREAD

**Issue by Dzieni** [pnp/pnpjs#2723]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.16

Please specify what version(s) of SharePoint you are targeting: online

### Expected / Desired Behavior / Question

`.addChunked` works when uploading a file in a long path.

### Observed Behavior

It fails with a following error: `The length of the URL for this request exceeds the configured maxUrlLength`

### Steps to Reproduce

Try to upload a file to a very long path, i.e.:

```await web.getFolderByServerRelativePath("!@p1::/sites/dzieni-test/Shared Documents/I am trying to make as long path as possible, let's see what happens/Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean turpis augue, hendrerit ut lorem condimentum, efficitur posuere enim/Maecenas tristique eleifend arcu. Nullam nec commodo felis, ac efficitur dolor/Donec eu dolor nec orci pharetra ultricies eu in urna").files.addChunked(...)```

**Comment by patrick-rodgers** [comment]
Thanks for reporting this. I am curious if there is a real use case to back this up?

Looking at you PR I see you fixed it for the single method in the extension - but wouldn't all of the files/folders methods require testing and validation against your long path? I am hesitant to apply a single fix here as if this really is an issue affecting production code we should invest the time to fix it everywhere.

We just haven't had folks reporting production issues related to this functionality. Now, perhaps that is because these methods don't get a lot of usage, or folks are missing the errors.

In the past we looked at having alias parameters for all the file/folder calls all the time, but the complexity vs value didn't support the effort as it just doesn't come up in real usage.

**Comment by Dzieni** [comment]
>wouldn't all of the files/folders methods require testing and validation against your long path?

You're absolutely right, all the calls that use `ServerRelativeUrl` internally should be investigated. For some reason I thought this construction is used only in Node extensions, but I see a lot of such calls in the other parts of the library.

>I am curious if there is a real use case to back this up?

Well, that's how I found this bug 😄. At @StratoKit we use PNP to synchronize files to SharePoint and one of our customers didn't receive some files due to the URL length error. For sure it is not common as we've been running the product for a few years already and it popped out it last week. In any case, the bug has been triggered completelly organically.
