### ISSUE TITLE
Why isn't there a graph.me.followedSites() function in pnpjs 3.

### ISSUE THREAD

**Issue by erikjvanderveen** [pnp/pnpjs#2824]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3

### Expected / Desired Behavior / Question

Why isn't there a graph.me.followedSites() function in pnpjs 3. I understand there is a SP function for that, but I guess MS wants users to move over to MS Graph if possible.

**Comment by juliemturner** [comment]
So first, Microsoft can want whatever they want but that doesn't mean we have to comply. I absolutely use the Microsoft Graph endpoints when it makes sense, but if it doesn't, because I'm working in SharePoint and the SharePoint REST endpoints are faster for instance, then I don't.

To answer your question though, it's not there because this is a community lead effort that is entirely voluntary. As maintainers we do all of this work in our free time. There is a back story to why there wasn't more graph coverage in V3 but at this point its water under the bridge and I'm not going to rehash it. That said we are underway in our V4 implementation, and our goal is to try and get full graph coverage. In the meantime, you can call any graph endpoint you want by utilizing the extension objects documented here: https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/#microsoft-graph

Also, if you would like to contribute, please feel free: https://pnp.github.io/pnpjs/contributing/

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
