### ISSUE TITLE
SearchQueryBuilder and resultsURL

### ISSUE THREAD

**Issue by JazzHoolahawk** [pnp/pnpjs#2829]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx (1.17.4) web part for SharePoint online. 

@pnp/sp/search

### Question/Request

I have a custom form and I want the results to redirect to a search page rather than display on the form page.

I have an issue with trying to get the resultsURL to do anything and I am struggling to find an example to get it to work.

```
const builder = SearchQueryBuilder(this.state.searchText, appSearchSettings)            
            .enableInterleaving
            .enableQueryRules
            .enableSorting
            .processPersonalFavorites
            .resultsURL("https://MyDomain.sharepoint.com/sites/testsite/SitePages/Search.aspx");
const results: SearchResults = await this._sp.search(builder);

// for testing
console.log(results3);
console.log(results3.RowCount);
console.log(results3.PrimarySearchResults);
```

I am obviously confused, if anyone is able to assist I would be appreciative :)

Cheers.

**Comment by juliemturner** [comment]
If I understand you correctly, you're suggesting that by providing the resultsUrl property to the query builder that the REST call will result in a redirect to that page with the results of the query?

If you could explain your end goal scenario more, I might be able to direct you.

**Comment by JazzHoolahawk** [comment]
> If I understand you correctly, you're suggesting that by providing the resultsUrl property to the query builder that the REST call will result in a redirect to that page with the results of the query?
> 
> If you could explain your end goal scenario more, I might be able to direct you.

Hi Julie,

Thank you for your reply, if is really appreciated :)

- I have been tasked with building a custom search form with multiple form fields.
- My organisation is using PnP Modern Search (v4) web parts for search results
- Because of the feature set, we hope to use Modern Search to display the results of any search using the custom form.
- We are also hoping to using PnPJs SP Search library to capture the query from the form and either a) send the query to the modern search results page or b) send the query result to the modern search page.

I was thinking that it might be possible using the resultsURL parameter to sent the query or results to the search result page, but I am not sure if this is how this works.

Happy to hear any input your could provide on this :) The other possibility is to have a custom result page but wanted to avoid this if possible.

Cheers,
David

**Comment by bcameron1231** [comment]
So I think you'll want to re-think how you're doing this. You definitely wouldn't want to execute a search request and then go to the search page, because the Search Page is going to execute the request all over again. What you would just want to do in your form, is collect all the values to construct your search query text, and then pass a query text string or the parameters to the Search Result page that has your Modern Search Web Part on it.

1. Construct the entire KQL query text yourself from your form data.
2. Navigate User to Modern Search Page, Pass query over with a query string parameter
3. Configure Modern Search Web Part query template to get the query text from the url parameter
4. Let Modern Search Web Part process your results.

Something similar to how this scenario works.
https://microsoft-search.github.io/pnp-modern-search/scenarios/use-query-string-in-url/
