### ISSUE TITLE
How to send recurrence emails without using Power Automate?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2928]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx

### Question/Request

Hello All,

I am using SharePoint Online and I have created one list for store Requests.

This list contains columns like Title, Description, Start Date, End Date, etc..

I have created an SPFx solution for inserting/updating/deleting data from the Requests list.

I have used @pnp/sp/utilities to send an email while inserting/updating items in the Requests list.

There is one column End date in the Request list.

Now, I need to send a reminder email after 2 days of the End Date.

Can anyone suggest a way to send an email without using Power Automate (Flow)?

Thanks

**Comment by juliemturner** [comment]
Azure Function with a timer trigger.

**Comment by bhoomesh-spe** [comment]
@juliemturner - Thanks for the quick response. Can I use that in the SPFx React solution?

**Comment by juliemturner** [comment]
[Azure functions](https://azure.microsoft.com/en-us/products/functions/?ef_id=_k_84ad04ca9fa11d4716d1617667e587ef_k_&OCID=AIDcmm5edswduu_SEM__k_84ad04ca9fa11d4716d1617667e587ef_k_&msclkid=84ad04ca9fa11d4716d1617667e587ef) aren't related to the SharePoint Framework and since there is no UI, ReactJS isn't part of it. Essentially, it's just a bit of code (can be TypeScript/Javascript running on NodeJS, C# running on .NET, PowerShell, and a whole host of other languages) that is triggered on a timer to run. By the name you might infer that it runs in Azure and you would need a subscription, although depending on how frequently you run it and how much it does it would likely be free or next to free. You would authorize the Azure function to access your SharePoint environment through managed identity and a service principal, but you would have to have access enough in Azure to do that or you'd need someone with that level of access to grant it for you.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
