### ISSUE TITLE
Adding Excel workbook support

### ISSUE THREAD

**Issue by ChapC** [pnp/pnpjs#3016]
### Target environment

All

### Enhancement Idea

Hi there!

I've been working with PnPJS to interact with Graph APIs for a few months now (thanks, btw!) and I recently found the need to use some of the Excel Workbook related endpoints. I couldn't see a library package for these operations, so I started implementing a few of the endpoints under a 'workbook' extension on DriveItem. 

At the moment I only have a few of the most simple operations (creating sessions, listing rows, tables), but I'll likely need to create more. I was wondering if this is something you guys would accept a PR for? The API doesn't seem overly complicated, so I'd be open to typing out the workbook, table and rows sections to start. Just thought I'd check to see if it's up for grabs, or if your team is already on top of it.

Thanks again for all your work on this library. Finding these kind of client libraries for an API is a dream :)

**Comment by juliemturner** [comment]
Absolutely, we'd love to see a PR for this. That said we would not implement it directly in drive item. You would create a new folder for workbook and then extend drive item. You can see examples of this for other endpoints sortof like [lists](https://github.com/pnp/pnpjs/tree/version-4/packages/graph/lists) but since workbook only exists off drive items then you really could implement the pattern that's in `drive.ts` directly in `index.ts`... although it's fine to separate them too...

**Comment by ChapC** [comment]
Great! I've created a draft pull request with some further questions and notes in there 👍
