### ISSUE TITLE
I want to re-authenticate into my SharePoint site on button click or after any event occur.

### ISSUE THREAD

**Issue by sagarMehta1907** [pnp/pnpjs#3102]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx React

### Question/Request

Hello Everyone,

I want to re-authenticate into my SharePoint site using MFA after any events occur or click on a button.
I have developed the application into the SPFx framework with React JS.

Please guide me on how to do and implement this in my code.

Thanks.

**Comment by patrick-rodgers** [comment]
What things have you tried? Where are you stuck? Can you share any code you've tried?

**Comment by juliemturner** [comment]
There's a tenant setting now that automatically logs your users out after an amount of time you set. I think that might be the better answer to what you're looking for.

**Comment by sagarMehta1907** [comment]
@patrick-rodgers 
Not have any idea about how to implement this functionality, What I need to use, and what is required.

**Comment by sagarMehta1907** [comment]
@juliemturner 
Thanks, But I want to call that event after click event.

**Comment by patrick-rodgers** [comment]
@sagarMehta1907 - we aren't able to provide custom solution work. If you get to a point and are stuck using the library we will do our best to assist.

**Comment by bcameron1231** [comment]
In addition, because you're using SPFx, Microsoft is handling the authentication for you, PnPjs is not. There is nothing we can do as part of the library to assist in this. If you're viewing the SPFx Web Part, it means you're already authenticated. 

I am going close this ticket because it is a non-library issue. As Patrick mentioned, if you end up using the library and have a question please open a new issue we'll do our best to assist.
