### ISSUE TITLE
URLs as parameters should encode ' as ''

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#313]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.2.1     ]

Please specify what version(s) of SharePoint you are targeting: [   2013? not sure ]

### Observed Behavior

When trying to access an item by url when there's a `'` in the path, pnpjs produces a URL like

`web/getFolderByServerRelativeUrl('/Workspaces/PROJECT1/Shared Documents/Graham's Stuff')/listItemAllFields`

This fails.

The correct version is

`web/getFolderByServerRelativeUrl('/Workspaces/PROJECT1/Shared Documents/Graham''s Stuff')/listItemAllFields`

So just double up any `'`. `%27` is not accepted by SP.

**Comment by koltyakov** [comment]
Thank you @wmertens! Interesting observation. Yep, looks like a bug.

**Comment by patrick-rodgers** [comment]
Typically we don't do any encoding of characters within paths. This has been because there are too many possibilities so we leave that to the caller to correctly ensure their path's are sanitized. Having a ' char in a path is atypical. My concern is that if we start encoding we will forever be chasing our tails. Perhaps what we should do is add an article on encoding. We can call out this case specifically as well as others that come in.

**Comment by patrick-rodgers** [comment]
Also #56 and #156.

**Comment by pedro-pedrosa** [comment]
Well I would guess that this happens everywhere where string parameters are sent in the URL. So having a ' char in a string may not be so atypical.

Personally I dislike the idea of having to encode parameters in user code, mostly because the user has no idea how those parameters are going to be handled. If they go in the URL they should be URL encoded and, in the case of string literals, single quotes replaced with double quotes, while if they go in a POST body they shouldn't be escaped at all. By leaving this to the user you're forcing the user to use a "try and see if it works" approach...

I don't understand the many languages argument. `encodeURIComponent` should do everything for you in terms of character encoding. Doubling up single quotes solves the quote character issue in strings. Is there any other case I'm missing?

**Comment by wmertens** [comment]
I disagree - this library abstracts away the HTTP layer needed to talk to Sharepoint, as well as all the esoteric knowledge needed to use that layer.

Having to quote `'` as `''` is highly surprising and has nothing to do with URL encoding, and everything with sharepoint and its weird path quoting.

The actual call I'm doing is

```js
const {ServerRelativeUrl} = await someFile.get()
const url = ServerRelativeUrl.slice(0, ServerRelativeUrl.lastIndexOf('/'))
const folder = web.getFolderByServerRelativeUrl(url)
// ...
```

in other words, I'm expecting the urls that the API returns to be the same ones I can use to make calls with the API, but in this case that is not true.

**Comment by patrick-rodgers** [comment]
If we do this we will need to gate it, otherwise it is a breaking change and we would have to bump the library major version. Something like a flag in sp.setup and maybe graph.setup for "escapeFilePaths" or something. False by default, but set to true and we will escape the paths. We'd have to update each file/folder related method and retest each. Then we would I think want a util function like "makePathSafe" or similar and normalize on using that everywhere. That way any fixes can be done in one spot.

**Comment by thunderknot** [comment]
Hi,

I was having the same issue trying to call the SP REST API from a workflow, but there is two ways to work around this:

1. [BEST solution] If you have the ID of the folder you can easily overcome this problem, even to another special character, because this way you don't need to bother with them on your call:
[YOUR_SITE_URL]/_api/web/lists/GetByTitle('YOUR_LIST_NAME')/Items(ID_OF_THE_FOLDER)/Folder/ListItemAllFields

[YOUR_SITE_URL]/_api/web/lists/GetByTitle('YOUR_LIST_NAME')/Items(ID_OF_THE_ITEM)/File/ListItemAllFields

This also works for GetById(LIST_ID).

2. If you have to work only with the URLs, you would need to change your call to GetFileByServerRelativePath, use the decodeurl parameter and also encode your URL. Note that for single quotes (only them) you also need to double the quotes occurrences.
REST call url (also works for files with GetFileByServerRelativePath): 

[YOUR_SITE_URL]/_api/web/GetFolderByServerRelativePath(decodedurl='%2Fsites%2Fsite_collection%2FDocument%20Library%2FCheckup%20%27%27apostrophe%27%27%20a')/ListItemAllFields

Where my server relative for the folder is /sites/site_collection/Document Library/Checkup 'apostrophe' a

**Comment by ltdu** [comment]
I agree with @wmertens and @pedro-pedrosa on this issue. Library should take care of handling provided values if they are used in URL.
* replace ```'``` with ```''```
* always use aliases i.e. ```/_api/web/lists/GetByTitle(@p1)?@p1='ListTitle'```
* encode all query parameters

I don't mind having a switch in configuration which enables this feature to help with transition.

**Comment by wmertens** [comment]
@ltdu what does the aliasing do, does it work around URL length issues? In that case, that would be great, there are files I can't reach because I can't figure out their list-id and the SP installation has a very low URL size limit.

If you do aliasing, does `'` still need to be converted to `''`?

**Comment by ltdu** [comment]
@wmertens here is great article about alias use in pnpjs: https://pnp.github.io/pnpjs/sp/docs/alias-parameters. Alias does not change the fact that you have to deal with ```'``` yourself.

**Comment by patrick-rodgers** [comment]
We are working to include the change to handle ' char in 2.0.

**Comment by wmertens** [comment]
@patrick-rodgers I just noticed that parameters also need to be URL encoded.

This means I need to move files like this:

```js
	const serverUrl = (await folder.get()).ServerRelativeUrl

	const newPath = [...serverUrl.split('/'), name]
		.map(encodeURIComponent)
		.join('/')
		.replace(/'/g, "''")
	await file.moveTo(newPath)
```

Which is easy to overlook when you're using this library, and in fact it took me almost a year to notice it.

On top of that, `moveTo` doesn't support aliases (or pnpmjs doesn't handle it, not sure), to add #613 into the mix and making me worried about trying to move a file into a too-long path.

I really think these factors all point to the case that v2.0 should completely wrap the SP REST API. It's impossible to know all the nooks and crannies of that API and this library is in the best position to abstract it all away.

**Comment by thw0rted** [comment]
Did this get resolved?  I'm looking at some `filter` examples in [the current docs](https://pnp.github.io/pnpjs/sp/items/) and they even give a placeholder that would fail if sent as-is: ` .filter(`Hidden eq false and Title eq '[Field's_Display_Name]'`)` -- note the possessive apostrophe.

Is the current version smart enough to doctor all `filter` arguments such that a quote inside a quoted literal is automatically converted to `''`?  If so, the docs should at least make a note of this.  If not, the docs should explain exactly what the restrictions are and how to work around them.  (And, I'd argue, maybe we need a smarter `filter()` method, so the user doesn't have to worry about it.)
