### ISSUE TITLE
Add Link in NewDocumentTemplates

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#319]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **1.6.0**

Please specify what version(s) of SharePoint you are targeting: **Online**

### Expected / Desired Behavior / Question
Is it possible to programmatically add "Link" item in the modern view of a created Document library? I have code in SPFx web part that creates Document Library, and users would prefer having that "Link" item there after doclib creation and not having to manually add it to new DocLibs via "Edit New Menu".

![image](https://user-images.githubusercontent.com/6917905/47705625-bef37500-dc2f-11e8-976e-0a4c8d6c0600.png)

I can see from browser traces that there is a call made to `/sites/somesite/_api/web/GetList(@a1)/DefaultView/SetViewXml()?@a1=%27%2Fsites%2Fsomesite%2FMyDocumentLibrary%27` with payload containing `...{"title":"Link","visible":true}]</NewDocumentTemplates>`, so it is possible, but is there perhaps a neater way to just add one item to NewDocumentTemplates using PnP without manually constructing the XML, and making REST POST call, etc.?

**Comment by patrick-rodgers** [comment]
This isn't something I have tried before, but if there is REST support for it we should be able to add it. Will have a look.

**Comment by patrick-rodgers** [comment]
In #367 I have added support for the setViewXml method.

I considered adding helper methods to manage things like menu links or row limit but decided against adding them because you could write an entire library on managing the viewXml string. For now you can get the existing view xml, modify it, and then call setViewXml to update the view, links included. It would be a great idea for a community library that allows you to easily parse the xml that folks could optionally use, but I feel like it would be more code than makes sense to add for folks that don't need it. Hope this helps get you going, even though it doesn't provide a single method call to update the links.
