### ISSUE TITLE
Convert internals of the library to use await

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#369]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question

Previously we avoided using await internally in the library due to the amount of helper code that generated when transpiling. Now that modern browser all support await natively we can transition to updating things to use await. Folks supporting older browsers will be stuck with larger file sizes, but the trade-off is worth it to simplify things within the library.

**Comment by AustinBreslinDev** [comment]
Hi @patrick-rodgers ,

I thought of helping out on this enhancement, but to make sure that I am on the right track is this the kind of thing you are asking for?

https://github.com/AustinBreslinDev/pnpjs/tree/asyncMethodModifier

I noticed that some (If I had to guess around 10 public methods already use Async), so I decided to apply it to all methods.

I didn't submit a pull request because I'm not 100% sure if this is what you were looking for. If it is, let me know.

**Comment by patrick-rodgers** [comment]
Hi @AustinBreslinDev - appreciate your willingness to take this on, but would caution you it is a big change that will likely not be merged for a bit as we aren't ready to flip to 2.0. This one wasn't really posted looking for help (though that is always welcome) as much as it was to help layout future roadmap for the eventual 2.0 release.

The change really deals with updating the internals of many methods that do some async operation within the method and currently chain on .then(... . These would be updated to be async and internally use await.

I didn't see where you made changes because you linked to the root of your cloned repo and I didn't know where you wanted me to look.

**Comment by patrick-rodgers** [comment]
Unless a method needs to await something within its body there isn't a need to add async to the signature. We'll look at updating just those that need it.

In some cases we may continue to use the "then" pattern, depends on what makes sense in each case. As you note it might be better depending.
