### ISSUE TITLE
get subsite list items

### ISSUE THREAD

**Issue by peterremote1980** [pnp/pnpjs#454]
Hi
    If i browse to https://quantr.sharepoint.com/peter/  , sp.web.lists.getByTitle("Staff") will read the list in a subsite call peter

   But If i browse to https://quantr.sharepoint.com/peter  , sp.web.lists.getByTitle("Staff") will read the list in a root site, since the url doesn't end with a '/'

I think it is a bug, right?

thanks
From Peter

**Comment by koltyakov** [comment]
Hi @peterremote1980,

I suppose that you have SPFx webpart on a home page, don't you?
With SPFx, a context should be bind using sp.setup, [see more](
https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpcommon-setup).

Also, a web can be defined implicitly using `const web = new Web('[Web_Absolute_Url]')`.

**Comment by peterremote1980** [comment]
const web = new Web('[Web_Absolute_Url]') this one not working when the url doesn't have a slash at the end too.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of information. Have tested this with urls without a trailing slash and things work as expected. I believe this is an issue [as mentioned](https://github.com/pnp/pnpjs/issues/454#issuecomment-454087255) with not using the setup method. Please open a new issue if you continue to have trouble or are able to provide a minimal reproduction. Thanks!
