### ISSUE TITLE
pnp.sp is undefined when including @pnp/sp-taxonomy

### ISSUE THREAD

**Issue by stact** [pnp/pnpjs#464]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 1.1.4 ]

### Expected / Desired Behavior / Question
Work with @pnp/sp and @pnp/sp-taxonomy
What are the steps to include sp-taxonomy and bundle a package like pnpjs manually, without webpack? It seems there is no package with all packages (@pnp/sp and @pnp/sp-taxonomy)

### Observed Behavior
When including @pnp/pnpjs bundle, all is fine, we can work with pnp.sp as expected.
But when we include @pnp/pnpjs and @pnp/sp-taxonomy bundles (because sp-taxonomy not included in pnpjs bundle), pnp.taxonomy works and pnp.sp is undefined.

### Steps to Reproduce
Include to your SharePoint site those 2 scripts:
https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.1.4/pnpjs.es5.umd.bundle.js
https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-taxonomy/1.1.4/sp-taxonomy.es5.umd.bundle.js

I tried to used only umd files, not working.
I tried also to use https://github.com/pnp/pnpjs/tree/dev/tools/generator-package
but no documentation or a sample to allow us to understand this tool.

Hope you could help us to find a way to package or find a package that includes pnp.sp and pnp.taxonomy! Thanks!

**Comment by patrick-rodgers** [comment]
Hi @stact - Can you share your code (or a link to a repo we can clone to see the issue) to allow us to see how you are including things? I am also not sure what you mean by "bundle a package like pnpjs manually, without webpack"? Are you just adding script tags to the page?

The generator-package tool isn't for folks to use, it is something we use if we are adding a new package to the library - hence no docs or samples for that.

The sp-taxonomy package is not included in the large pnpjs bundle because we may eventually have a better option (real rest support for manage metadata) which we can add to the sp library. That would then be included in the larger pnpjs bundle. Then we would have to make another breaking change to remove the taxonomy library.

**Comment by stact** [comment]
Hi @patrick-rodgers 
Unfortunately we don't have a repo to share, yes we are juste including in our master page those bundles:
https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.1.4/pnpjs.es5.umd.bundle.js
https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-taxonomy/1.1.4/sp-taxonomy.es5.umd.bundle.js

And after in our components, we try to use pnp.sp.web.lists.get() (for example) : that's works fine with only including pnpjs.es5.umd.bundle.js
but when we are including sp-taxonomy.es5.umd.bundle.js  we have this error: 
`"TypeError: Cannot read property 'web' of undefined"`

We are not able to find a hack or a method to allow us to work with pnp.sp and pnp.taxonomy simultaneously. What is the best practice to include those libraries, and how?

It's a good news to include taxonomy to pnpjs core, is a roadmap to know when this package will be included?

**Comment by stact** [comment]
With 1.2.8 version of pnpjs and sp-taxonomy it seems to have no conflict.
We can access to pnp.sp functionalities, but not pnp.taxonomy or something else to deal with taxonomy. We made a hack on bundle to work with. 
```javascript
pnp.taxonomy = factory().taxonomy;
```

We are waiting for a pnpjs bundle with managed metadata support.
Thx for your help @patrick-rodgers
