### ISSUE TITLE
Refused to set unsafe header "user-agent" - es5

### ISSUE THREAD

**Issue by NicolasR** [pnp/pnpjs#482]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [**1.2.6**]

Please specify what version(s) of SharePoint you are targeting: [**SharePoint 2013 On-Premise**]

### Expected / Desired Behavior / Question
Must not show an error on console. Maybe i'm missing something.

### Observed Behavior
I have an error on console when I do a request: _Refused to set unsafe header "user-agent"_
All is working perfectly but this error remains in console.

### Steps to Reproduce
Include **pnpjs.es5.umd.bundle.min.js** in a page.
Do a request, for example:
```
pnp.sp.web.get().then(w => {
        console.log(JSON.stringify(w, null, 4));
    });
```

**Comment by patrick-rodgers** [comment]
The throttling strategy used by SPO (and all of Office365) is to check [for a specific user agent](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic-to-avoid-throttling). We add that string to each request - BUT all browsers block setting the user agent. This fact has been communicated to the folks that own that functionality. We leave the code in for folks working in node or other server based environments where you can set that string. So this is by design and you can safely ignore that console entry.

**Comment by NicolasR** [comment]
I understand.
Thank you for your quick answer.
