### ISSUE TITLE
Missing function toHtml()

### ISSUE THREAD

**Issue by umaknow-annie** [pnp/pnpjs#571]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.1-1 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question

I used the function ```toHtml()``` of the class ClientSideWebpart in 1.2.9 version of pnpjs but it no longer exists. Is there a way to get the html of a ClientSideWebPart?

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Correct, this function was removed because we no longer parse the html from the list item fields, rather we updated the library to use an entirely different back-end API as discussed in #504. Depending on what you are trying to do there might be a way to accomplish the same thing. Can you describe the scenario you need?

**Comment by umaknow-annie** [comment]
I used the html to get all the link in a WebPart

**Comment by patrick-rodgers** [comment]
Sorry - not quite enough to go on. Do you mean that you extracted them from the ClientTextPart in content or what? If you can describe what you are trying to do we can try and offer solutions, but we need the details.

**Comment by umaknow-annie** [comment]
We are doing an extension to copy pages. When copying a Web Part, we parse the html to have links that point to the current site. Then, in the new page, we replace the links for those we want in the destination site.

**Comment by patrick-rodgers** [comment]
You would need to find a new solution to solving that problem. If it is a ClientSideText you can use the `text` property which will be the full html and you can do that operation there. For other types of webparts I am not sure what the best way to access that content would be as they would all have different "shapes" for how they store data. This is however by design and the toHtml isn't something we will add back as we are using an entirely different API now that doesn't require it.
