### ISSUE TITLE
[2.0.0] sub module: SP-security

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#661]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by russgove** [comment]
Hi, I can work on this.

**Comment by PopWarner** [comment]
Awesome!!! Thank you @russgove! Status has been changed to "in progress" and is all ready for ya. :)

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thank you again!

**Comment by russgove** [comment]
So whats everyone doing for tests. I need a  site a user a list and a list item in order to test security.
Can we make any assumptions about the environment the test is running in? Will there be a 'Shared Documents' library?

Seems like everyone will need some setup work like this. Might be helpful if we could define some standard test environment, maybe gets deployed via a script so that we can start with a clean environment every time.

**Comment by russgove** [comment]
In the documentation, what approach is everyone else taking for code snippets. I think, ideally, the code snippets should be able to be pasted into a VSCode window and executed.   The existing samples I see lack the required startup code.  

It would be nice if all the samples be set so that they could be pasted into debug\launch\sp.ts and then run via f5 debugging.

**Comment by PopWarner** [comment]
Hi @russgove.....apologies for the delay on getting back to you.

Let me try to address some of your questions. :)

> I need a site a user a list and a list item in order to test security.
Anything that is needed for your testing would be generated with your tests. If your needing a user, list or list item, then the test would create those for purposes of the test.

> Can we make any assumptions about the environment the test is running in? 
No assumptions are expected to be made about the environment. This would further support the discussion above about needing to create anything needed for purposes of testing.

> In the documentation, what approach is everyone else taking for code snippets. 
@juliemturner just finished the SP-Fields sub module and mentioned that you might want to look at her PR for her approach, as she believes there are some similarities that will be beneficial for you.
https://github.com/pnp/pnpjs/issues/632

Thanks again for all your help! :)

**Comment by patrick-rodgers** [comment]
Going to grab this one to close it out. For some of the issues raised feel free to open a new issue to discuss - will keep this focused on completing the sub-module.
