### ISSUE TITLE
[2.0.0] sub module: SP-webparts

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#674]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by JonasBjerke89** [comment]
I could grap this one, too. Please sign me up :-)

**Comment by PopWarner** [comment]
Very cool! Thank you @JonasBjerke89! The status has been updated to "in progress" and is ready for you.

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thank you again!

**Comment by JonasBjerke89** [comment]
Hi @PopWarner 

I have been working on this and a few obstacles came along:
1. The current implementation of the "import" method gives me an empty SP.WebParts.WebPartDefinition and a HTTP 200 in return (JSOM API). The ID of the returned webpart definition is an empty guid. This seems wrong to me.
2. Secondly, we cannot automate tests of the "export" method because the "addWebPart" method is not implemented. This means that we cannot write a testcase that creates a new page, inserts a webpart, which we then could manipulate. Furthermore, we cannot write tests for working with the webpart definition ifself for the same reason.

Should we just accept the fact that the JSOM api properly isn't the best for working with webparts and page modifications, and ignore it? I can refer to this issue as well: https://github.com/SharePoint/PnP-JS-Core/issues/485

Please let me know what you think is the best way forward.

**Comment by JonasBjerke89** [comment]
@patrick-rodgers Any thoughts on this?

**Comment by patrick-rodgers** [comment]
The webparts API in REST is kinda junky. I would write tests for what you can and leave a comment in the file stating that we can't write tests for XYZ and why. That will remind us when we review everything. And like I said in the other issue much of the API hasn't changed in years to won't get better or worse.
