### ISSUE TITLE
Cannot read property 'sectionFactor' of undefined

### ISSUE THREAD

**Issue by mstivoi** [pnp/pnpjs#681]
### Category
- [] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue
### Version
Please specify what version of the library you are using: [  1.3.2]
Please specify what version(s) of SharePoint you are targeting: [   Online      ]
### Expected / Desired Behavior / Question

I have this code in SPFx extension: 
 ClientSidePage.fromFile(pnp.sp.site.rootWeb.getFileByServerRelativeUrl(pageUrl)).then((response: ClientSidePage) => { })
I have checked , pageUrl is correct , page exists . But i am getting error : 

Uncaught (in promise) TypeError: Cannot read property 'sectionFactor' of undefined
    at CanvasColumn.fromHtml (clientsidepages.js:538)
    at clientsidepages.js:267
    at getBoundedDivMarkup (clientsidepages.js:102)
    at ClientSidePage.fromHtml (clientsidepages.js:257)
    at clientsidepages.js:293
What i see exactl at line 538

CanvasColumn.prototype.fromHtml = function (html) {
        _super.prototype.fromHtml.call(this, html);
        this.controlData = ClientSidePage.escapedStringToJson(getAttrValueFromString(html, "data-sp-controldata"));
        this.factor = this.controlData.position.sectionFactor;  //538 - position is undefined.
        this.order = this.controlData.position.sectionIndex;
    };
This issue is similar to #410  but  i did not call "fromHtml" .

**Comment by patrick-rodgers** [comment]
Hi @mstivoi - if you are getting those errors you are not in fact using 1.3.2 as [they no longer exist in the library](https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/clientsidepages.ts). Would ask that you please ensure you are on the latest version of the library and try again, we had to fully re-write things due to backend API changes a few months ago. Give that a shot and let us know if you continue to see errors. Thanks!

**Comment by mstivoi** [comment]
Yes . Used old repository . New one become much better . Closing issue.
