### ISSUE TITLE
SharePoint Authentication - Client side | AWS Cognito - Azure AD

### ISSUE THREAD

**Issue by tarundhillon** [pnp/pnpjs#760]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ ] Documentation gap/issue

Hello, 

I have a web app hosted on AWS which authenticates via AWS Cognito -- SAML - Azure AD, the authentication process gives me access_token and id_token which I believe are issued by AWS Cognito through Azure AD. I am able to exchange these tokens to get AWS credentials and access AWS resources, but  some of my resources are  on SharePoint and I was wondering how do I go about authentication to access them ? 

Any suggestions or direction will be much appreciated.

**Comment by koltyakov** [comment]
I don't think the existing token clients will work with this schema, but I might be wrong.

My inner feeling on how this should work:

- AWS Cognito to Azure AD should be configured [such way](https://medium.com/@zippicoder/setup-aws-cognito-user-pool-with-an-azure-ad-identity-provider-to-perform-single-sign-on-sso-7ff5aa36fc2a)
- Azure AD is configured with App Registration, App Registration's permissions setup for commuting with SharePoint Online/Graph API, etc. and having a required access level
- A custom AWS Cognito awared [fetchClientFactory](https://pnp.github.io/pnpjs/common/docs/custom-httpclientimpl/) should be implemented with [amazon-cognito-auth-js](https://github.com/aws/amazon-cognito-auth-js) or whatever is used currently for getting tokens
- If you already have a token for an API resource [BearerTokenFetchClient](https://github.com/pnp/pnpjs/blob/59fbb1ead47ef95bf199f6b265f6897d5d12f531/packages/common/src/netutil.ts#L60) can be used, otherwise a token should be acquired for a specific resource

Can recommend asking the question also in [Gitter](https://gitter.im/OfficeDev/PnP-JS-Core) I know there were some folk who got to solve different interesting authentication cases.

**Comment by tarundhillon** [comment]
Thanks Andrew ! I can confirm the same token doesn't work, the token is issues by Cognito. Able to complete 1,2 and 3 but struggling with step 4 seems like some permission errors  

I am using ADAL through an angular package with the below configuration 
    ```
MsAdalAngular6Module.forRoot({
      tenant: 'bf322cf0-59ea-474b-aa22-xxxxx',
      clientId: 'cdb70e6e-7bf9-4836-a907-xxxxxx',
      // redirectUri: window.location.origin,
      endpoints: {
        api: 'https://xxxx.sharepoint.com' 
      },
      redirectUri: 'http://localhost:4200/public/azure-callback',
      navigateToLoginRequestUrl: false,
      cacheLocation: 'localStorage', 
    })
```

I am able to fetch the token but facing issues to access sharepoint with the below snippet 

```
 let urlSite = "https://cors-anywhere.herokuapp.com/https://xxx.sharepoint.com/sites/xxxx";
    this.adalSvc.acquireToken('api')
      .subscribe(token=>{
        console.log('adal token',token); 

        console.log('userinfo', this.adalSvc.userInfo, this.adalSvc.GetResourceForEndpoint('api'));
        const client = new BearerTokenFetchClient(token);
        client.fetch(urlSite, {});
        
      });
```

I am getting  **401 Unauthorized** but i can see  **authorization: Bearer eyJ0eXxxx**-- token in the request. 

Additionally in the Azure AD App I have given the following API permissions 

SharePoint (2) - AllSites.FullControl, AllSites.Manage
Microsoft Graph (5) - User.Read

Any suggestions ?? I will also try out Gitter later

**Comment by patrick-rodgers** [comment]
Going to close this as non-library. Thanks!
