### ISSUE TITLE
How to push changes made to site columns at web level down to libraries using that field

### ISSUE THREAD

**Issue by NigelWit** [pnp/pnpjs#959]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version(s) of SharePoint you are targeting: [ SP Online        ]

When updating a site column, how do you force the update to be pushed to all ContentTypes and libraries using that field?

e.g. the following code updates the available choices in a multichoice field at the web level, but this change is not reflected in the libraries using content types that have that field:

```
this.web.fields.getByInternalNameOrTitle(fieldName).update(
            {
              Choices: {
                results: [itemTitle]
              } as any
            },
            "SP.FieldMultiChoice"
          );
```

Thanks!!

**Comment by koltyakov** [comment]
This might be not possible via REST API, that's the first which comes to mind. Needed to be investigated. Not directly related to PnPjs but REST API. If you know the way to promote "update all child entities" with REST rather than detect such entities and iterate through them with updates, that would be helpful. Maybe @olemp solved this within sp-js-provisioning?

**Comment by patrick-rodgers** [comment]
Going to close this as the option to push changes down is not available via REST so far as I can find. If there is a way happy to have it added. Thanks!
