### ISSUE TITLE
Strong typing of graph queries

### ISSUE THREAD

**Issue by semopz** [pnp/pnpjs#979]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
When using a `select`, the resolved object should contain only the properties fed into `select`. Also you should not be able to pass strings to `select` that do not exist on the queried object. Here's a function that does this:
```typescript
import { MSGraphClient } from "@microsoft/sp-http";
import { User } from "@microsoft/microsoft-graph-types";

type UserProperties = keyof User;

// https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#common-properties
type DefaultUserProperties = 'id' |
  'businessPhones' |
  'displayName' |
  'givenName' |
  'jobTitle' |
  'mail' |
  'mobilePhone' |
  'officeLocation' |
  'preferredLanguage' |
  'surname' |
  'userPrincipalName';

export async function whoAmI <Props extends UserProperties[] = DefaultUserProperties[]> (client: MSGraphClient, selectProperties?: Props) {
  type Selected = typeof selectProperties[number];
  const user: { [P in Selected]?: User[P]; } = await client
    .api('me')
    .version('v1.0')
    .select(selectProperties)
    .get();
  return user;
}
```
And here it is in action
Default properties
![Default properties only](https://i.imgur.com/yc5ZN7V.png)

Only selected properties
![Selecting properties](https://i.imgur.com/7FZcIeB.png)

You can't pass properties that don't exist on the API
![Not allowed](https://i.imgur.com/k12cN8k.png)
### Observed Behavior
The response is any
![Response is of any type](https://i.imgur.com/pJ4WDib.png)

The correct type is in there somewhere
![Response is still any but select knows the correct type](https://i.imgur.com/tVppB7Z.png)

This kind of works
```typescript
import { graph } from '@pnp/graph/presets/all';
import { User } from "@microsoft/microsoft-graph-types";

async () => {
  const myProfile = await graph.me.select('id')<User>();
  
  // This won't work but TS hasn't picked it up
  const myName = myProfile.surname;
}
```
![Correct type but too many properties](https://i.imgur.com/1LPjxZt.png)

**Comment by patrick-rodgers** [comment]
Sure, but is is rather complex to implement in a way that doesn't break things. Yes, is it easy to write a single function that shows this behavior - much harder to add it into the entire library in a way that works consistently across all of the operations, works as expected, and doesn't block folks from doing other things because we have restricted the typings. For example: how would you represent expands on that result object and in the select?

We had someone do some work in this area previously but there were a number of cases it didn't handle. And, truth be told I spent a fair few hours working again on this problem for v2 but you end up running into too many cases where either things don't end up working as expected OR you block folks from being able to do something because the typings don't resolve "correctly".

You can always type your result to be what is actually coming back. Perhaps not fancy, but does ensure your result is typed exactly as you expect. And you only have to do that work once in the places it really matters and forget about it. You could also use (to take your example):

```TypeScript
const myProfile = await graph.me.select("id")<Pick<User, "id">>();
```

All that being said, if you can come up with a way to do it that works consistently across collections, individual objects, expands, selects, and all the rest I absolutely welcome it - but as I said in the past I am not sure of the value of adding that complexity over just typing the result.

**Comment by semopz** [comment]
Fair enough. I wouldn't be able to suggest a better way of doing it. Expands are definitely a tough nut to crack (and probably not possible unless you go with GraphQL). It's a shame that whoever comes up with the budgets for creating Graph APIs thinks that citizen tooling is for the community to sort out for themselves.

Thanks for your suggestion as well. I have been considering it but I'm always worried that if I decide to update the function at a future date, I might add a property to the generic but then forget to pass it to the select (if you're fatigued it might not be easy to spot that bug quickly).

I guess this enhancement request is denied? I don't have anything useful to add but at least I now know that this has been considered.

**Comment by patrick-rodgers** [comment]
There are official [Graph SDKs available](https://developer.microsoft.com/en-us/graph/get-started/javascript) as well - perhaps they have features you may prefer to what we can offer.

It isn't that it is denied as much as I haven't found a way to fully make it work. This is a side gig for me and I may revisit trying to implement it at some point, but don't have an estimated timeline and it isn't currently a priority. As I mentioned I did spend a decent amount of time trying to make it work for v2 but ran into too many obstacles to be happy with it. Lots of folks smarter than me so welcome ideas - but it does need to cover all the scenarios.

Appreciate your feedback, they are good ideas - will certainly keep it in mind.

**Comment by patrick-rodgers** [comment]
Going to close this as there are no open questions. As mentioned this is a good idea - just not something we have a clear path to implement at this time. Will absolutely keep it in mind for the future. Thanks!
