### ISSUE TITLE
[Search] Cannot get next page results by function getPage(pageNumber)

### ISSUE THREAD

**Issue by SkyleOri** [pnp/pnpjs#991]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **2.0.0**

Please specify what version(s) of SharePoint you are targeting: **SharePoint 2013**

### Expected Behavior
*The search results of the next page.*

### Observed Behavior
*The post response return error message: "The search request cannot be empty."*

### Steps to Reproduce
- Step 1: Get the result: sp.search(queryOptions)
- Step 2: After receiving the results, call result.getPage(pageNumber)
- Step 3: Observe the result from step 2

**Comment by KEMiCZA** [comment]
I suspect this is related to https://github.com/pnp/pnpjs/issues/975
We need to wait until the next release for this fix to become available.

**Comment by nmnikolov** [comment]
I have the same issue. After applying the fix for #975  manually in file quarable.js in node_modules then I get the same error when trying to get a page using Search Api. I noticed that the endpoint contains  _api/search/postquery twice:

![Search_issue](https://user-images.githubusercontent.com/7761113/71719482-2b1acb80-2e27-11ea-8fd0-dafff6dc9580.png)

**Comment by patrick-rodgers** [comment]
I think this is fixed, closing the issue. Thanks all!
